// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 43: // ['+','+']
			return 2
		case r == 45: // ['-','-']
			return 3
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 49: // ['0','1']
			return 5
		case 50 <= r && r <= 57: // ['2','9']
			return 6
		case r == 59: // [';',';']
			return 7
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 8
		case r == 97: // ['a','a']
			return 9
		case r == 98: // ['b','b']
			return 9
		case r == 99: // ['c','c']
			return 9
		case r == 100: // ['d','d']
			return 10
		case r == 101: // ['e','e']
			return 11
		case 102 <= r && r <= 104: // ['f','h']
			return 8
		case r == 105: // ['i','i']
			return 12
		case 106 <= r && r <= 122: // ['j','z']
			return 8
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 13
		case r == 47: // ['/','/']
			return 14
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case 48 <= r && r <= 49: // ['0','1']
			return 5
		case 50 <= r && r <= 57: // ['2','9']
			return 6
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 6
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 107: // ['a','k']
			return 16
		case r == 108: // ['l','l']
			return 17
		case 109 <= r && r <= 122: // ['m','z']
			return 16
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 101: // ['a','e']
			return 16
		case r == 102: // ['f','f']
			return 18
		case 103 <= r && r <= 122: // ['g','z']
			return 16
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 19
		default:
			return 13
		}
	},
	// S14
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 20
		default:
			return 14
		}
	},
	// S15
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 114: // ['a','r']
			return 16
		case r == 115: // ['s','s']
			return 21
		case 116 <= r && r <= 122: // ['t','z']
			return 16
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 19
		case r == 47: // ['/','/']
			return 22
		default:
			return 13
		}
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 100: // ['a','d']
			return 16
		case r == 101: // ['e','e']
			return 23
		case 102 <= r && r <= 122: // ['f','z']
			return 16
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case 65 <= r && r <= 90: // ['A','Z']
			return 16
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 122: // ['a','z']
			return 16
		}
		return NoState
	},
}
