/*

https://en.wikipedia.org/wiki/Extended_Backus–Naur_form

Copyright (c) 2021 Tong Sun

*/

/* Lexical part */
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : _lineComment | _blockComment ;
_lineComment : '/' '/' {.} '\n' ;
_blockComment : '/' '*' {. | '*'} '*' '/' ;

id : _letter {_letter | _digit} ;

_letter : 'A' - 'Z' | 'a' - 'z' | '_' ;
_digit : '0' - '9' ;

number
  : [ '-' ] _digit { _digit }
  ;

char_lit
  : '"' (_unicode_value | _byte_value) '"'
  | '\'' (_unicode_value | _byte_value) '\''
  ;

string_lit
  : '"' {_unicode_char} '"' ;

_unicode_value    : _unicode_char | _little_u_value | _big_u_value | _escaped_char ;
_unicode_char
  : .                   // Any UTF-8 character literal
  ;
_byte_value       : _octal_byte_value | _hex_byte_value ;
_octal_byte_value : '\\' _octal_digit _octal_digit _octal_digit ;
_hex_byte_value   : '\\' 'x' _hex_digit _hex_digit ;
_little_u_value   : '\\' 'u' _hex_digit _hex_digit _hex_digit _hex_digit ;
_big_u_value      : '\\' 'U' _hex_digit _hex_digit _hex_digit _hex_digit
                            _hex_digit _hex_digit _hex_digit _hex_digit ;

_octal_digit : '0' - '7' ;
_hex_digit
  : '0' - '9'
  | 'A' - 'F'
  | 'a' - 'f'
  ;

_escaped_char : '\\' ( 'a' | 'b' | 'f' | 'n' | 'r' | 't' | 'v' | '\\' | '\'' | '"' ) ;


/* Syntax part */

Program
  : "PROGRAM" id
    ProgramDef
  ;

ProgramDef
  : BeginBlock
  | Procedure
    ProgramDef
  ;

Procedure
  : "PROCEDURE" id "()"
    BeginBlock
  ;

BeginBlock:
  : "BEGIN"
      ProgramBody
     "END." 
  ;

ProgramBody
  // { assignment ";" }
  : Assignment ";"
  | ProgramBody Assignment ";"
  | ForLoop
  | ProgramBody ForLoop ";"
  | empty
  ;

ForLoop
  : "FOR" Assignment "TO" number "DO"
      Assignment
  ;

// assignment = identifier , ":=" , ( number | identifier | string ) ;
Assignment
  : id ":=" RHS
  ;

RHS
  : id
  | string_lit
  | char_lit
  | number
  ;

