// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(4), // timestamp
			nil,      // taskLogStart
			nil,      // taskLogEnd
			nil,      // processLogStart
			nil,      // processLogEnd
			nil,      // jobLogStart
			nil,      // jobLogEnd
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // timestamp
			nil,          // taskLogStart
			nil,          // taskLogEnd
			nil,          // processLogStart
			nil,          // processLogEnd
			nil,          // jobLogStart
			nil,          // jobLogEnd
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: EventLog
			nil,       // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(7), // timestamp
			nil,      // taskLogStart
			nil,      // taskLogEnd
			nil,      // processLogStart
			nil,      // processLogEnd
			nil,      // jobLogStart
			nil,      // jobLogEnd
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // timestamp
			nil,      // taskLogStart
			nil,      // taskLogEnd
			nil,      // processLogStart
			nil,      // processLogEnd
			shift(8), // jobLogStart
			nil,      // jobLogEnd
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(10), // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(13), // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			shift(14), // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // timestamp, reduce: JobLogStart
			nil,        // taskLogStart
			nil,        // taskLogEnd
			nil,        // processLogStart
			nil,        // processLogEnd
			nil,        // jobLogStart
			nil,        // jobLogEnd
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: JobLog
			nil,       // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			shift(15), // jobLogEnd
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(18), // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(20), // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // timestamp
			shift(21), // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // timestamp, reduce: ProcessLogStart
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // $, reduce: JobLogEnd
			nil,        // timestamp
			nil,        // taskLogStart
			nil,        // taskLogEnd
			nil,        // processLogStart
			nil,        // processLogEnd
			nil,        // jobLogStart
			nil,        // jobLogEnd
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(3), // timestamp, reduce: ProcessLog
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(20), // timestamp
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // timestamp
			shift(21), // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			shift(23), // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(4), // timestamp, reduce: TaskLog
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // timestamp
			nil,       // taskLogStart
			shift(24), // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // timestamp, reduce: TaskLogStart
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(5), // timestamp, reduce: TaskLog
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // timestamp, reduce: ProcessLogEnd
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // timestamp, reduce: TaskLogEnd
			nil,       // taskLogStart
			nil,       // taskLogEnd
			nil,       // processLogStart
			nil,       // processLogEnd
			nil,       // jobLogStart
			nil,       // jobLogEnd
		},
	},
}
