/*

SQL-92 definitions gocc ebnf grammar

Copyright (c) 2022 Tong Sun

*/

/* Lexical part */
!whitespace : ' ' | '\t' | '\n' | '\r' ;
!comment : _lineComment | _blockComment ;
_lineComment : '/' '/' {.} '\n' ;
_blockComment : '/' '*' {. | '*'} '*' '/' ;

/* Lexical from sql-92.gocc.l.ebnf */

_exact_Numeric_Literal :
		_unsigned_Integer [ _period [ _unsigned_Integer ] ]
	|	_period _unsigned_Integer ;

_signed_Integer : [ _sign ] _unsigned_Integer ;

_character_Set_Name : [ _schema_Name _period ] _SQL_Language_Identifier ;

_schema_Name : [ _catalog_Name _period ] _unqualified_Schema_Name ;

_identifier : [ _introducercharacter_Set_Specification ] _actual_Identifier ;

_SQL_Language_Identifier :
		_SQL_Language_Identifier_Start [ { _underscore | _SQL_Language_Identifier_Part } ] ;

_table_Element_List : _left_Paren _table_Element [ { _comma _table_Element } ] _right_Paren ;

_column_Definition :
		_column_Name { _data_Type | _domain_Name } [ _default_Clause ] [ _column_Constraint_Definition {_column_Constraint_Definition} ] [ _collate_Clause ] ;

_data_Type :
		_character_String_Type [ 'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' 'S' 'E' 'T' _character_Set_Specification ]
	|	_national_Character_String_Type
	|	_bit_String_Type
	|	_numeric_Type
	|	_datetime_Type
	|	_interval_Type ;

_character_String_Type :
		'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' [ _left_Paren _length _right_Paren ]
	|	'C' 'H' 'A' 'R' [ _left_Paren _length _right_Paren ]
	|	'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' 'V' 'A' 'R' 'Y' 'I' 'N' 'G' [ _left_Paren _length _right_Paren ]
	|	'C' 'H' 'A' 'R' 'V' 'A' 'R' 'Y' 'I' 'N' 'G' [ _left_Paren _length _right_Paren ]
	|	'V' 'A' 'R' 'C' 'H' 'A' 'R' [ _left_Paren _length _right_Paren ] ;

_national_Character_String_Type :
		'N' 'A' 'T' 'I' 'O' 'N' 'A' 'L' 'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' [ _left_Paren _length _right_Paren ]
	|	'N' 'A' 'T' 'I' 'O' 'N' 'A' 'L' 'C' 'H' 'A' 'R' [ _left_Paren _length _right_Paren ]
	|	'N' 'C' 'H' 'A' 'R' [ _left_Paren _length _right_Paren ]
	|	'N' 'A' 'T' 'I' 'O' 'N' 'A' 'L' 'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' 'V' 'A' 'R' 'Y' 'I' 'N' 'G' [ _left_Paren _length _right_Paren ]
	|	'N' 'A' 'T' 'I' 'O' 'N' 'A' 'L' 'C' 'H' 'A' 'R' 'V' 'A' 'R' 'Y' 'I' 'N' 'G' [ _left_Paren _length _right_Paren ]
	|	'N' 'C' 'H' 'A' 'R' 'V' 'A' 'R' 'Y' 'I' 'N' 'G' [ _left_Paren _length _right_Paren ] ;

_bit_String_Type :
		'B' 'I' 'T' [ _left_Paren _length _right_Paren ]
	|	'B' 'I' 'T' 'V' 'A' 'R' 'Y' 'I' 'N' 'G' [ _left_Paren _length _right_Paren ] ;

_exact_Numeric_Type :
'	' 	'N' 'U' 'M' 'E' 'R' 'I' 'C' [ _left_Paren _precision [ _comma _scale ] _right_Paren ]
	| 	'D' 'E' 'C' 'I' 'M' 'A' 'L' [ _left_Paren _precision [ _comma _scale ] _right_Paren ]
	| 	'D' 'E' 'C' [ _left_Paren _precision [ _comma _scale ] _right_Paren ]
	|	'I' 'N' 'T' 'E' 'G' 'E' 'R'
	|	'I' 'N' 'T'
	|	'S' 'M' 'A' 'L' 'L' 'I' 'N' 'T' ;

_approximate_Numeric_Type :
'	' 	'F' 'L' 'O' 'A' 'T' [ _left_Paren _precision _right_Paren ]
	|	'R' 'E' 'A' 'L'
	|	'D' 'O' 'U' 'B' 'L' 'E' 'P' 'R' 'E' 'C' 'I' 'S' 'I' 'O' 'N' ;

_datetime_Type :
		'D' 'A' 'T' 'E'
	|   'T' 'I' 'M' 'E' [ _left_Paren _time_Precision _right_Paren ] [ 'W' 'I' 'T' 'H' 'T' 'I' 'M' 'E' 'Z' 'O' 'N' 'E' ]
	|   'T' 'I' 'M' 'E' 'S' 'T' 'A' 'M' 'P' [ _left_Paren _timestamp_Precision _right_Paren ] [ 'W' 'I' 'T' 'H' 'T' 'I' 'M' 'E' 'Z' 'O' 'N' 'E' ] ;

_start_Field :
		_non_second_Datetime_Field [ _left_Paren _interval_Leading_Field_Precision _right_Paren ] ;

_end_Field :
		_non_second_Datetime_Field
	|   'S' 'E' 'C' 'O' 'N' 'D' [ _left_Paren _interval_Fractional_Seconds_Precision _right_Paren ] ;

_single_Datetime_Field :
		_non_second_Datetime_Field [ _left_Paren _interval_Leading_Field_Precision _right_Paren ]
	|   'S' 'E' 'C' 'O' 'N' 'D' [ _left_Paren _interval_Leading_Field_Precision [ _comma _interval_Fractional_Seconds_Precision ] _right_Paren ] ;

_qualified_Name : [ _schema_Name _period ] _qualified_Identifier ;

_signed_Numeric_Literal : [ _sign ] _unsigned_Numeric_Literal ;

_interval_Literal : 'I' 'N' 'T' 'E' 'R' 'V' 'A' 'L' [ _sign ] _interval_String _interval_Qualifier ;

_current_Time_Value_Function : 'C' 'U' 'R' 'R' 'E' 'N' 'T' '_' 'T' 'I' 'M' 'E' [ _left_Paren _time_Precision _right_Paren ] ;

_current_Timestamp_Value_Function : 'C' 'U' 'R' 'R' 'E' 'N' 'T' '_' 'T' 'I' 'M' 'E' 'S' 'T' 'A' 'M' 'P' [ _left_Paren _timestamp_Precision _right_Paren ] ;

_identifier_Body : _identifier_Start [ { _underscore | _identifier_Part } ] ;

_national_Character_String_Literal :
		'N' _quote [ _character_Representation {_character_Representation} ] _quote [ { _separator {_separator} _quote [ _character_Representation {_character_Representation} ] _quote } ] ;

_bit_String_Literal :
		'B' _quote [ _bit {_bit} ] _quote [ { _separator {_separator} _quote [ _bit {_bit} ] _quote } ] ;

_hex_String_Literal :
		'X' _quote [ _hexit {_hexit} ] _quote [ { _separator {_separator} _quote [ _hexit {_hexit} ] _quote } ] ;

_character_String_Literal :
	[ _introducercharacter_Set_Specification ] _quote [ _character_Representation {_character_Representation} ] _quote [ { _separator {_separator} _quote [ _character_Representation {_character_Representation} ] _quote } ] ;

_time_String : _quote _time_Value [ _time_Zone_Interval ] _quote ;

_seconds_Value : _seconds_Integer_Value [ _period [ _seconds_Fraction ] ] ;

_timestamp_String : _quote _date_Value _space _time_Value [ _time_Zone_Interval ] _quote ;

_interval_String : _quote { _year_month_Literal | _day_time_Literal } _quote ;

_left_Paren : '(' ;

_right_Paren : ')' ;

_asterisk : '*' ;

_plus_Sign : '+' ;

_comma : ',' ;

_minus_Sign : '-' ;

_period : '.' ;

_solidus : '/' ;

_colon : ':' ;

_less_Than_Operator : '<' ;

_equals_Operator : '=' ;

_greater_Than_Operator : '>' ;

_question_Mark : '?' ;

_unsigned_Numeric_Literal :
		_exact_Numeric_Literal
	|	_approximate_Numeric_Literal ;

_unsigned_Integer : _digit {_digit} ;

_approximate_Numeric_Literal :
		_mantissa 'E' _exponent ;

_mantissa : _exact_Numeric_Literal ;

_exponent : _signed_Integer ;

_sign : _plus_Sign | _minus_Sign ;

_character_Set_Specification :
		_standard_Character_Repertoire_Name
	|	_implementation_defined_Character_Repertoire_Name
	|	_user_defined_Character_Repertoire_Name
	|	_standard_Universal_Character_Form_of_use_Name
	|	_implementation_defined_Universal_Character_Form_of_use_Name ;

_standard_Character_Repertoire_Name : _character_Set_Name ;

_catalog_Name : _identifier ;

_actual_Identifier : _regular_Identifier | _delimited_Identifier ;

_delimited_Identifier : _double_Quote _delimited_Identifier_Body _double_Quote ;

_delimited_Identifier_Body : _delimited_Identifier_Part {_delimited_Identifier_Part} ;

_unqualified_Schema_Name : _identifier ;

_SQL_Language_Identifier_Start : _simple_Latin_Letter ;

_SQL_Language_Identifier_Part : _simple_Latin_Letter | _digit ;

_greater_Than_Or_Equals_Operator : '>' '=' ;

_less_Than_Or_Equals_Operator : '<' '=' ;

_concatenation_Operator : '|' '|' ;

_authorization_Identifier : _identifier ;

_qualified_Local_Table_Name : 'M' 'O' 'D' 'U' 'L' 'E' _period _local_Table_Name ;

_local_Table_Name : _qualified_Identifier ;

_qualified_Identifier : _identifier ;

_table_Element : _column_Definition | _table_Constraint_Definition ;

_column_Name : _identifier ;

_length : _unsigned_Integer ;

_numeric_Type :
		_exact_Numeric_Type
	|	_approximate_Numeric_Type ;

_precision : _unsigned_Integer ;

_scale : _unsigned_Integer ;

_time_Precision : _time_Fractional_Seconds_Precision ;

_time_Fractional_Seconds_Precision : _unsigned_Integer ;

_timestamp_Precision : _time_Fractional_Seconds_Precision ;

_interval_Type : 'I' 'N' 'T' 'E' 'R' 'V' 'A' 'L' _interval_Qualifier ;

_interval_Qualifier :
		_start_Field 'T' 'O' _end_Field
	|   _single_Datetime_Field ;

_interval_Leading_Field_Precision : _unsigned_Integer ;

_interval_Fractional_Seconds_Precision : _unsigned_Integer ;

_domain_Name : _qualified_Name ;

_default_Clause : 'D' 'E' 'F' 'A' 'U' 'L' 'T' _default_Option ;

_default_Option :
		_literal
	|	_datetime_Value_Function
	|	'U' 'S' 'E' 'R'
	|	'C' 'U' 'R' 'R' 'E' 'N' 'T' '_' 'U' 'S' 'E' 'R'
	|	'S' 'E' 'S' 'S' 'I' 'O' 'N' '_' 'U' 'S' 'E' 'R'
	|	'S' 'Y' 'S' 'T' 'E' 'M' '_' 'U' 'S' 'E' 'R'
	|	'N' 'U' 'L' 'L' ;

_literal : _signed_Numeric_Literal | _general_Literal ;

_general_Literal :
		_character_String_Literal
	|	_national_Character_String_Literal
	|	_bit_String_Literal
	|	_hex_String_Literal
	|	_datetime_Literal
	|	_interval_Literal ;

_datetime_Literal :
		_date_Literal
	|	_time_Literal
	|	_timestamp_Literal ;

_date_Literal : 'D' 'A' 'T' 'E' _date_String ;

_time_Literal : 'T' 'I' 'M' 'E' _time_String ;

_timestamp_Literal : 'T' 'I' 'M' 'E' 'S' 'T' 'A' 'M' 'P' _timestamp_String ;

_datetime_Value_Function :
		_current_Date_Value_Function
	|	_current_Time_Value_Function
	|	_current_Timestamp_Value_Function ;

_current_Date_Value_Function : 'C' 'U' 'R' 'R' 'E' 'N' 'T' '_' 'D' 'A' 'T' 'E' ;

_simple_Latin_Letter :
		_simple_Latin_Upper_Case_Letter
	|	_simple_Latin_Lower_Case_Letter ;

_simple_Latin_Upper_Case_Letter :
	'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' ;

_simple_Latin_Lower_Case_Letter :
	'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' ;

_digit :
	'0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;

_double_Quote : '"' ;

_underscore : '_' ;

_regular_Identifier : _identifier_Body ;

_identifier_Part : _identifier_Start | _digit ;

_character_Representation : _nonquote_Character | _quote_Symbol ;

_quote_Symbol : _quote _quote ;

_bit : '0' | '1' ;

_hexit : _digit | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' ;

_date_String : _quote _date_Value _quote ;

_date_Value : _years_Value _minus_Sign _months_Value _minus_Sign _days_Value ;

_years_Value : _datetime_Value ;

_datetime_Value : _unsigned_Integer ;

_months_Value : _datetime_Value ;

_days_Value : _datetime_Value ;

_time_Value : _hours_Value _colon _minutes_Value _colon _seconds_Value ;

_hours_Value : _datetime_Value ;

_minutes_Value : _datetime_Value ;

_seconds_Integer_Value : _unsigned_Integer ;

_seconds_Fraction : _unsigned_Integer ;

_time_Zone_Interval : _sign _hours_Value _colon _minutes_Value ;

_quote : '\'' ;


/* Lexical from sql-92.p.definitions+.l.ebnf */



_schema_Definition : 'C' 'R' 'E' 'A' 'T' 'E' 'S' 'C' 'H' 'E' 'M' 'A' _schema_Name_Clause
			[ _schema_Character_Set_Specification ]
			[ _schema_Element {_schema_Element} ] ;

_table_Definition : 'C' 'R' 'E' 'A' 'T' 'E' [ { 'G' 'L' 'O' 'B' 'A' 'L' | 'L' 'O' 'C' 'A' 'L' } 'T' 'E' 'M' 'P' 'O' 'R' 'A' 'R' 'Y' ] 'T' 'A' 'B' 'L' 'E' _table_Name _table_Element_List [ 'O' 'N' 'C' 'O' 'M' 'M' 'I' 'T' { 'D' 'E' 'L' 'E' 'T' 'E' | 'P' 'R' 'E' 'S' 'E' 'R' 'V' 'E' } 'R' 'O' 'W' 'S' ] ;

_view_Definition : 'C' 'R' 'E' 'A' 'T' 'E' 'V' 'I' 'E' 'W' _table_Name [ _left_Paren _view_Column_List _right_Paren ]
			'A' 'S' _query_Expression [ 'W' 'I' 'T' 'H' [ _levels_Clause ] 'C' 'H' 'E' 'C' 'K' 'O' 'P' 'T' 'I' 'O' 'N' ] ;

_column_Name_List : _column_Name [ { _comma _column_Name } ] ;

_qualified_Join : _table_Reference [ 'N' 'A' 'T' 'U' 'R' 'A' 'L' ] [ _join_Type ] 'J' 'O' 'I' 'N' _table_Reference [ _join_Specification ] ;

_join_Type : 'I' 'N' 'N' 'E' 'R'
	|   _outer_Join_Type [ 'O' 'U' 'T' 'E' 'R' ]
	|   'U' 'N' 'I' 'O' 'N' ;

_boolean_Factor : [ 'N' 'O' 'T' ] _boolean_Test ;

_boolean_Test : _boolean_Primary [ 'I' 'S' [ 'N' 'O' 'T' ] _truth_Value ] ;

_factor : [ _sign ] _numeric_Primary ;

_parameter_Specification : _parameter_Name [ _indicator_Parameter ] ;

_indicator_Parameter : [ 'I' 'N' 'D' 'I' 'C' 'A' 'T' 'O' 'R' ] _parameter_Name ;

_variable_Specification : _embedded_Variable_Name [ _indicator_Variable ] ;

_indicator_Variable : [ 'I' 'N' 'D' 'I' 'C' 'A' 'T' 'O' 'R' ] _embedded_Variable_Name ;

_column_Reference : [ _qualifier _period ] _column_Name ;

_general_Set_Function : _set_Function_Type _left_Paren [ _set_Quantifier ] _value_Expression _right_Paren ;

_table_Reference : _table_Name [ _correlation_Specification ]
	|   _derived_Table _correlation_Specification
	|   _joined_Table ;

_correlation_Specification : [ 'A' 'S' ] _correlation_Name [ _left_Paren _derived_Column_List _right_Paren ] ;

_case_Abbreviation : 'N' 'U' 'L' 'L' 'I' 'F' _left_Paren _value_Expression _comma _value_Expression _right_Paren
	|	'C' 'O' 'A' 'L' 'E' 'S' 'C' 'E' _left_Paren _value_Expression { _comma _value_Expression }  _right_Paren ;

_simple_Case : 'C' 'A' 'S' 'E' _case_Operand
			_simple_When_Clause {_simple_When_Clause}
			[ _else_Clause ]
		'E' 'N' 'D' ;

_searched_Case : 'C' 'A' 'S' 'E'
		_searched_When_Clause {_searched_When_Clause}
		[ _else_Clause ]
		'E' 'N' 'D' ;

_character_Factor : _character_Primary [ _collate_Clause ] ;

_character_Substring_Function : 'S' 'U' 'B' 'S' 'T' 'R' 'I' 'N' 'G' _left_Paren _character_Value_Expression 'F' 'R' 'O' 'M' _start_Position [ 'F' 'O' 'R' _string_Length ] _right_Paren ;

_fold : { 'U' 'P' 'P' 'E' 'R' | 'L' 'O' 'W' 'E' 'R' } _left_Paren _character_Value_Expression _right_Paren ;

_trim_Operands : [ [ _trim_Specification ] [ _trim_Character ] 'F' 'R' 'O' 'M' ] _trim_Source ;

_bit_Substring_Function : 'S' 'U' 'B' 'S' 'T' 'R' 'I' 'N' 'G' _left_Paren _bit_Value_Expression 'F' 'R' 'O' 'M' _start_Position [ 'F' 'O' 'R' _string_Length ] _right_Paren ;

_interval_Factor : [ _sign ] _interval_Primary ;

_interval_Primary : _value_Expression_Primary [ _interval_Qualifier ] ;

_datetime_Factor : _datetime_Primary [ _time_Zone ] ;

_char_Length_Expression : { 'C' 'H' 'A' 'R' '_' 'L' 'E' 'N' 'G' 'T' 'H' | 'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' '_' 'L' 'E' 'N' 'G' 'T' 'H' } _left_Paren _string_Value_Expression _right_Paren ;

_row_Value_Constructor_List : _row_Value_Constructor_Element [ { _comma _row_Value_Constructor_Element } ] ;

_between_Predicate : _row_Value_Constructor [ 'N' 'O' 'T' ] 'B' 'E' 'T' 'W' 'E' 'E' 'N' _row_Value_Constructor 'A' 'N' 'D' _row_Value_Constructor ;

_in_Predicate : _row_Value_Constructor [ 'N' 'O' 'T' ] 'I' 'N' _in_Predicate_Value ;

_in_Value_List : _value_Expression { _comma _value_Expression } ;

_like_Predicate : _match_Value [ 'N' 'O' 'T' ] 'L' 'I' 'K' 'E' _pattern [ 'E' 'S' 'C' 'A' 'P' 'E' _escape_Character ] ;

_null_Predicate : _row_Value_Constructor 'I' 'S' [ 'N' 'O' 'T' ] 'N' 'U' 'L' 'L' ;

_match_Predicate : _row_Value_Constructor 'M' 'A' 'T' 'C' 'H' [ 'U' 'N' 'I' 'Q' 'U' 'E' ] [ 'P' 'A' 'R' 'T' 'I' 'A' 'L' | 'F' 'U' 'L' 'L' ] _table_Subquery ;


/*

_space : 'a';
_separator : 'a';
_escape_Character : 'a';
_nonquote_Character : 'a';
_numeric_Primary : 'a';
_character_Primary : 'a';
_datetime_Primary : 'a';
_boolean_Primary : 'a';
_value_Expression_Primary : 'a';
_day_time_Literal : 'a';
_year_month_Literal : 'a';
_parameter_Name : 'a';
_embedded_Variable_Name : 'a';
_correlation_Name : 'a';
_implementation_defined_Universal_Character_Form_of_use_Name : 'a';
_standard_Universal_Character_Form_of_use_Name : 'a';
_user_defined_Character_Repertoire_Name : 'a';
_implementation_defined_Character_Repertoire_Name : 'a';
_qualifier : 'a';
_set_Function_Type : 'a';
_trim_Source : 'a';
_trim_Character : 'a';
_trim_Specification : 'a';
_row_Value_Constructor : 'a';
_value_Expression : 'a';
_character_Value_Expression : 'a';
_string_Value_Expression : 'a';
_bit_Value_Expression : 'a';
_query_Expression : 'a';
_match_Value : 'a';
_in_Predicate_Value : 'a';
_truth_Value : 'a';
_joined_Table : 'a';
_derived_Table : 'a';
_table_Name : 'a';
_collate_Clause : 'a';
_searched_When_Clause : 'a';
_simple_When_Clause : 'a';
_else_Clause : 'a';
_schema_Name_Clause : 'a';
_levels_Clause : 'a';
_schema_Element : 'a';
_outer_Join_Type : 'a';
_join_Specification : 'a';
_table_Subquery : 'a';
_derived_Column_List : 'a';
_view_Column_List : 'a';
_case_Operand : 'a';
_pattern : 'a';
_introducercharacter_Set_Specification : 'a';
_schema_Character_Set_Specification : 'a';
_table_Constraint_Definition : 'a';
_column_Constraint_Definition : 'a';
_identifier_Start : 'a';
_start_Position : 'a';
_delimited_Identifier_Part : 'a';
_time_Zone : 'a';
_non_second_Datetime_Field : 'a';
_set_Quantifier : 'a';
_string_Length : 'a';

*/



/* Lexical from sql-92.p.definitions.l.ebnf */



_schema_Name_Clause :
		_schema_Name
	|	'A' 'U' 'T' 'H' 'O' 'R' 'I' 'Z' 'A' 'T' 'I' 'O' 'N' _schema_Authorization_Identifier
	|	_schema_Name 'A' 'U' 'T' 'H' 'O' 'R' 'I' 'Z' 'A' 'T' 'I' 'O' 'N' _schema_Authorization_Identifier ;

_schema_Authorization_Identifier : _authorization_Identifier ;

_schema_Character_Set_Specification : 'D' 'E' 'F' 'A' 'U' 'L' 'T' 'C' 'H' 'A' 'R' 'A' 'C' 'T' 'E' 'R' 'S' 'E' 'T' _character_Set_Specification ;

_view_Column_List : _column_Name_List ;

_levels_Clause : 'C' 'A' 'S' 'C' 'A' 'D' 'E' 'D' | 'L' 'O' 'C' 'A' 'L' ;

_table_Name : _qualified_Name | _qualified_Local_Table_Name ;

_query_Expression : _non_join__query_Expression | _joined_Table ;

_joined_Table :
		_cross_Join
	|   _qualified_Join
	|   _left_Paren _joined_Table _right_Paren ;

_cross_Join :
		_table_Reference 'C' 'R' 'O' 'S' 'S' 'J' 'O' 'I' 'N' _table_Reference ;

_outer_Join_Type : 'L' 'E' 'F' 'T' | 'R' 'I' 'G' 'H' 'T' | 'F' 'U' 'L' 'L' ;

_join_Specification : _join_Condition | _named_Columns_Join ;

_join_Condition : 'O' 'N' _search_Condition ;

_named_Columns_Join : 'U' 'S' 'I' 'N' 'G' _left_Paren _join_Column_List _right_Paren ;

_join_Column_List : _column_Name_List ;

_search_Condition :
		_boolean_Term
	|   _search_Condition 'O' 'R' _boolean_Term ;

_boolean_Term :
		_boolean_Factor
	|   _boolean_Term 'A' 'N' 'D' _boolean_Factor ;

_boolean_Primary : _predicate | _left_Paren _search_Condition _right_Paren ;

_predicate :
		_comparison_Predicate
	|   _between_Predicate
	|   _in_Predicate
	|   _like_Predicate
	|   _null_Predicate
	|   _quantified_Comparison_Predicate
	|   _exists_Predicate
	|   _match_Predicate
	|   _overlaps_Predicate ;

_comparison_Predicate : _row_Value_Constructor _comp_Op _row_Value_Constructor ;

_row_Value_Constructor :
		_row_Value_Constructor_Element
	|   _left_Paren _row_Value_Constructor_List _right_Paren
	|   _row_Subquery ;

_row_Value_Constructor_Element :
		_value_Expression
	|   _null_Specification
	|   _default_Specification ;

_value_Expression :
		_numeric_Value_Expression
	|   _string_Value_Expression
	|   _datetime_Value_Expression
	|   _interval_Value_Expression ;

_numeric_Value_Expression :
		_term
	|   _numeric_Value_Expression _plus_Sign _term
	|   _numeric_Value_Expression _minus_Sign _term ;

_term :
		_factor
	|   _term _asterisk _factor
	|   _term _solidus _factor ;

_numeric_Primary : _value_Expression_Primary | _numeric_Value_Function ;

_value_Expression_Primary :
		_unsigned_Value_Specification
	|   _column_Reference
	|   _set_Function_Specification
	|   _scalar_Subquery
	|   _case_Expression
	|   _left_Paren _value_Expression _right_Paren
	|   _cast_Specification ;

_unsigned_Value_Specification : _unsigned_Literal | _general_Value_Specification ;

_unsigned_Literal : _unsigned_Numeric_Literal | _general_Literal ;

_general_Value_Specification :
		_parameter_Specification
	|   _dynamic_Parameter_Specification
	|   _variable_Specification
	|   'U' 'S' 'E' 'R'
	|   'C' 'U' 'R' 'R' 'E' 'N' 'T' '_' 'U' 'S' 'E' 'R'
	|   'S' 'E' 'S' 'S' 'I' 'O' 'N' '_' 'U' 'S' 'E' 'R'
	|   'S' 'Y' 'S' 'T' 'E' 'M' '_' 'U' 'S' 'E' 'R'
	|   'V' 'A' 'L' 'U' 'E' ;

_parameter_Name : _colon _identifier ;

_dynamic_Parameter_Specification : _question_Mark ;

_embedded_Variable_Name : _colonHost_Identifier ;

_qualifier : _table_Name | _correlation_Name ;

_correlation_Name : _identifier ;

_set_Function_Specification :
		'C' 'O' 'U' 'N' 'T' _left_Paren _asterisk _right_Paren
	|   _general_Set_Function ;

_set_Function_Type : 'A' 'V' 'G' | 'M' 'A' 'X' | 'M' 'I' 'N' | 'S' 'U' 'M' | 'C' 'O' 'U' 'N' 'T' ;

_set_Quantifier : 'D' 'I' 'S' 'T' 'I' 'N' 'C' 'T' | 'A' 'L' 'L' ;

_scalar_Subquery : _subquery ;

_subquery : _left_Paren _query_Expression _right_Paren ;

_derived_Column_List : _column_Name_List ;

_derived_Table : _table_Subquery ;

_table_Subquery : _subquery ;

_case_Expression : _case_Abbreviation | _case_Specification ;

_case_Specification : _simple_Case | _searched_Case ;

_case_Operand : _value_Expression ;

_else_Clause : 'E' 'L' 'S' 'E' _result ;

_cast_Specification : 'C' 'A' 'S' 'T' _left_Paren _cast_Operand 'A' 'S' _cast_Target _right_Paren ;

_cast_Operand : _value_Expression | 'N' 'U' 'L' 'L' ;

_cast_Target : _domain_Name | _data_Type ;

_numeric_Value_Function : _position_Expression | _extract_Expression |	_length_Expression ;

_position_Expression :
	'P' 'O' 'S' 'I' 'T' 'I' 'O' 'N' _left_Paren _character_Value_Expression 'I' 'N' _character_Value_Expression _right_Paren ;

_character_Value_Expression : _concatenation | _character_Factor ;

_concatenation : _character_Value_Expression _concatenation_Operator _character_Factor ;

_character_Primary : _value_Expression_Primary | _string_Value_Function ;

_string_Value_Function : _character_Value_Function | _bit_Value_Function ;

_character_Value_Function :
		_character_Substring_Function
	|   _fold
	|   _form_of_use__conversion
	|   _character_Translation
	|   _trim_Function ;

_start_Position : _numeric_Value_Expression ;

_string_Length : _numeric_Value_Expression ;

_character_Translation :
		'T' 'R' 'A' 'N' 'S' 'L' 'A' 'T' 'E' _left_Paren _character_Value_Expression 'U' 'S' 'I' 'N' 'G' _translation_Name _right_Paren ;

_translation_Name : _qualified_Name ;

_trim_Function : 'T' 'R' 'I' 'M' _left_Paren _trim_Operands _right_Paren ;

_trim_Specification : 'L' 'E' 'A' 'D' 'I' 'N' 'G' | 'T' 'R' 'A' 'I' 'L' 'I' 'N' 'G' | 'B' 'O' 'T' 'H' ;

_trim_Character : _character_Value_Expression ;

_trim_Source : _character_Value_Expression ;

_bit_Value_Function : _bit_Substring_Function ;

_bit_Value_Expression : _bit_Concatenation | _bit_Factor ;

_bit_Concatenation : _bit_Value_Expression _concatenation_Operator _bit_Factor ;

_bit_Factor : _bit_Primary ;

_bit_Primary : _value_Expression_Primary | _string_Value_Function ;

_extract_Expression : 'E' 'X' 'T' 'R' 'A' 'C' 'T' _left_Paren _extract_Field 'F' 'R' 'O' 'M' _extract_Source _right_Paren ;

_extract_Field : _datetime_Field | _time_Zone_Field ;

_datetime_Field : _non_second__datetime_Field | 'S' 'E' 'C' 'O' 'N' 'D' ;

_time_Zone_Field : 'T' 'I' 'M' 'E' 'Z' 'O' 'N' 'E' '_' 'H' 'O' 'U' 'R' | 'T' 'I' 'M' 'E' 'Z' 'O' 'N' 'E' '_' 'M' 'I' 'N' 'U' 'T' 'E' ;

_extract_Source : _datetime_Value_Expression | _interval_Value_Expression ;

_datetime_Value_Expression :
		_datetime_Term
	|	_interval_Value_Expression _plus_Sign _datetime_Term
	|	_datetime_Value_Expression _plus_Sign _interval_Term
	|	_datetime_Value_Expression _minus_Sign _interval_Term ;

_interval_Term :
		_interval_Factor
	|	_interval_Term_2 _asterisk _factor
	|	_interval_Term_2 _solidus _factor
	|	_term _asterisk _interval_Factor ;

_interval_Term_2 : _interval_Term ;

_interval_Value_Expression :
		_interval_Term
	|	_interval_Value_Expression_1 _plus_Sign _interval_Term_1
	|	_interval_Value_Expression_1 _minus_Sign _interval_Term_1
	|	_left_Paren _datetime_Value_Expression _minus_Sign _datetime_Term _right_Paren _interval_Qualifier ;

_interval_Value_Expression_1 : _interval_Value_Expression ;

_interval_Term_1 : _interval_Term ;

_datetime_Term : _datetime_Factor ;

_datetime_Primary : _value_Expression_Primary | _datetime_Value_Function ;

_time_Zone : 'A' 'T' _time_Zone_Specifier ;

_time_Zone_Specifier : 'L' 'O' 'C' 'A' 'L' | 'T' 'I' 'M' 'E' 'Z' 'O' 'N' 'E' _interval_Value_Expression ;

_length_Expression : _char_Length_Expression | _octet_Length_Expression | _bit_Length_Expression ;

_string_Value_Expression : _character_Value_Expression | _bit_Value_Expression ;

_octet_Length_Expression : 'O' 'C' 'T' 'E' 'T' '_' 'L' 'E' 'N' 'G' 'T' 'H' _left_Paren _string_Value_Expression _right_Paren ;

_bit_Length_Expression : 'B' 'I' 'T' '_' 'L' 'E' 'N' 'G' 'T' 'H' _left_Paren _string_Value_Expression _right_Paren ;

_null_Specification : 'N' 'U' 'L' 'L' ;

_default_Specification : 'D' 'E' 'F' 'A' 'U' 'L' 'T' ;

_row_Subquery : _subquery ;

_comp_Op :
		_equals_Operator
	|   _not_Equals_Operator
	|   _less_Than_Operator
	|   _greater_Than_Operator
	|   _less_Than_Or_Equals_Operator
	|   _greater_Than_Or_Equals_Operator ;

_in_Predicate_Value : _table_Subquery | _left_Paren _in_Value_List _right_Paren ;

_match_Value : _character_Value_Expression ;

_pattern : _character_Value_Expression ;

_escape_Character : _character_Value_Expression ;

_quantified_Comparison_Predicate : _row_Value_Constructor _comp_Op _quantifier _table_Subquery ;

_quantifier : _all | _some ;

_all : 'A' 'L' 'L' ;

_some : 'S' 'O' 'M' 'E' | 'A' 'N' 'Y' ;

_exists_Predicate : 'E' 'X' 'I' 'S' 'T' 'S' _table_Subquery ;

_overlaps_Predicate : _row_Value_Constructor_1 'O' 'V' 'E' 'R' 'L' 'A' 'P' 'S' _row_Value_Constructor_2 ;

_row_Value_Constructor_1 : _row_Value_Constructor ;

_row_Value_Constructor_2 : _row_Value_Constructor ;

_truth_Value : 'T' 'R' 'U' 'E' | 'F' 'A' 'L' 'S' 'E' | 'U' 'N' 'K' 'N' 'O' 'W' 'N' ;

_collate_Clause : 'C' 'O' 'L' 'L' 'A' 'T' 'E' _collation_Name ;

_collation_Name : _qualified_Name ;

_result : _result_Expression | 'N' 'U' 'L' 'L' ;

_result_Expression : _value_Expression ;

