// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 39: // [''',''']
			return 3
		case r == 40: // ['(','(']
			return 4
		case r == 41: // [')',')']
			return 5
		case r == 42: // ['*','*']
			return 6
		case r == 43: // ['+','+']
			return 6
		case r == 45: // ['-','-']
			return 7
		case r == 46: // ['.','.']
			return 8
		case r == 47: // ['/','/']
			return 9
		case r == 58: // [':',':']
			return 10
		case r == 59: // [';',';']
			return 11
		case r == 63: // ['?','?']
			return 6
		case 65 <= r && r <= 90: // ['A','Z']
			return 12
		case r == 91: // ['[','[']
			return 13
		case r == 93: // [']',']']
			return 14
		case r == 95: // ['_','_']
			return 12
		case 97 <= r && r <= 122: // ['a','z']
			return 12
		case r == 123: // ['{','{']
			return 15
		case r == 124: // ['|','|']
			return 16
		case r == 125: // ['}','}']
			return 17
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 18
		case r == 92: // ['\','\']
			return 19
		default:
			return 20
		}
	},
	// S3
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 18
		case r == 92: // ['\','\']
			return 21
		default:
			return 22
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 23
		case r == 47: // ['/','/']
			return 24
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 58: // [':',':']
			return 25
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 26
		case 65 <= r && r <= 90: // ['A','Z']
			return 12
		case r == 95: // ['_','_']
			return 12
		case 97 <= r && r <= 122: // ['a','z']
			return 12
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 93: // [']',']']
			return 27
		default:
			return 28
		}
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 29
		case r == 39: // [''',''']
			return 29
		case 48 <= r && r <= 55: // ['0','7']
			return 30
		case r == 85: // ['U','U']
			return 31
		case r == 92: // ['\','\']
			return 29
		case r == 97: // ['a','a']
			return 29
		case r == 98: // ['b','b']
			return 29
		case r == 102: // ['f','f']
			return 29
		case r == 110: // ['n','n']
			return 29
		case r == 114: // ['r','r']
			return 29
		case r == 116: // ['t','t']
			return 29
		case r == 117: // ['u','u']
			return 32
		case r == 118: // ['v','v']
			return 29
		case r == 120: // ['x','x']
			return 33
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 34
		default:
			return 35
		}
	},
	// S21
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 36
		case r == 39: // [''',''']
			return 36
		case 48 <= r && r <= 55: // ['0','7']
			return 37
		case r == 85: // ['U','U']
			return 38
		case r == 92: // ['\','\']
			return 36
		case r == 97: // ['a','a']
			return 36
		case r == 98: // ['b','b']
			return 36
		case r == 102: // ['f','f']
			return 36
		case r == 110: // ['n','n']
			return 36
		case r == 114: // ['r','r']
			return 36
		case r == 116: // ['t','t']
			return 36
		case r == 117: // ['u','u']
			return 39
		case r == 118: // ['v','v']
			return 36
		case r == 120: // ['x','x']
			return 40
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 34
		default:
			return 41
		}
	},
	// S23
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 42
		default:
			return 23
		}
	},
	// S24
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 43
		default:
			return 24
		}
	},
	// S25
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 44
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 26
		case 65 <= r && r <= 90: // ['A','Z']
			return 12
		case r == 95: // ['_','_']
			return 12
		case 97 <= r && r <= 122: // ['a','z']
			return 12
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case r == 93: // [']',']']
			return 27
		default:
			return 28
		}
	},
	// S29
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 45
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 46
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		case 65 <= r && r <= 70: // ['A','F']
			return 47
		case 97 <= r && r <= 102: // ['a','f']
			return 47
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 70: // ['A','F']
			return 48
		case 97 <= r && r <= 102: // ['a','f']
			return 48
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 49
		case 65 <= r && r <= 70: // ['A','F']
			return 49
		case 97 <= r && r <= 102: // ['a','f']
			return 49
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 18
		default:
			return 35
		}
	},
	// S36
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 45
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 50
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case 65 <= r && r <= 70: // ['A','F']
			return 51
		case 97 <= r && r <= 102: // ['a','f']
			return 51
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 70: // ['A','F']
			return 52
		case 97 <= r && r <= 102: // ['a','f']
			return 52
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 70: // ['A','F']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 53
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 18
		default:
			return 41
		}
	},
	// S42
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 42
		case r == 47: // ['/','/']
			return 54
		default:
			return 23
		}
	},
	// S43
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 55
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 56
		case 65 <= r && r <= 70: // ['A','F']
			return 56
		case 97 <= r && r <= 102: // ['a','f']
			return 56
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 70: // ['A','F']
			return 57
		case 97 <= r && r <= 102: // ['a','f']
			return 57
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case 65 <= r && r <= 70: // ['A','F']
			return 58
		case 97 <= r && r <= 102: // ['a','f']
			return 58
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 55: // ['0','7']
			return 59
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 60
		case 65 <= r && r <= 70: // ['A','F']
			return 60
		case 97 <= r && r <= 102: // ['a','f']
			return 60
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		case 65 <= r && r <= 70: // ['A','F']
			return 61
		case 97 <= r && r <= 102: // ['a','f']
			return 61
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 62
		case 65 <= r && r <= 70: // ['A','F']
			return 62
		case 97 <= r && r <= 102: // ['a','f']
			return 62
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 45
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 63
		case 65 <= r && r <= 70: // ['A','F']
			return 63
		case 97 <= r && r <= 102: // ['a','f']
			return 63
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 64
		case 65 <= r && r <= 70: // ['A','F']
			return 64
		case 97 <= r && r <= 102: // ['a','f']
			return 64
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 45
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 45
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 65
		case 65 <= r && r <= 70: // ['A','F']
			return 65
		case 97 <= r && r <= 102: // ['a','f']
			return 65
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 66
		case 65 <= r && r <= 70: // ['A','F']
			return 66
		case 97 <= r && r <= 102: // ['a','f']
			return 66
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 45
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 67
		case 65 <= r && r <= 70: // ['A','F']
			return 67
		case 97 <= r && r <= 102: // ['a','f']
			return 67
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		case 65 <= r && r <= 70: // ['A','F']
			return 68
		case 97 <= r && r <= 102: // ['a','f']
			return 68
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case 65 <= r && r <= 70: // ['A','F']
			return 69
		case 97 <= r && r <= 102: // ['a','f']
			return 69
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 70
		case 65 <= r && r <= 70: // ['A','F']
			return 70
		case 97 <= r && r <= 102: // ['a','f']
			return 70
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case 65 <= r && r <= 70: // ['A','F']
			return 71
		case 97 <= r && r <= 102: // ['a','f']
			return 71
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 45
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 45
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 73
		case 65 <= r && r <= 70: // ['A','F']
			return 73
		case 97 <= r && r <= 102: // ['a','f']
			return 73
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 74
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 75
		case 65 <= r && r <= 70: // ['A','F']
			return 75
		case 97 <= r && r <= 102: // ['a','f']
			return 75
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case 65 <= r && r <= 70: // ['A','F']
			return 76
		case 97 <= r && r <= 102: // ['a','f']
			return 76
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 77
		case 65 <= r && r <= 70: // ['A','F']
			return 77
		case 97 <= r && r <= 102: // ['a','f']
			return 77
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 78
		case 65 <= r && r <= 70: // ['A','F']
			return 78
		case 97 <= r && r <= 102: // ['a','f']
			return 78
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 45
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 45
		}
		return NoState
	},
}
