// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Stmt
		3,  // If_stmt
		2,  // Expr
		5,  // Term
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		13, // Expr
		14, // Term
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		20, // Term
	},
	gotoRow{ // S13
		-1, // S'
		21, // Stmt
		23, // If_stmt
		22, // Expr
		5,  // Term
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		28, // Expr
		14, // Term
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		29, // Term
	},
	gotoRow{ // S26
		-1, // S'
		30, // Stmt
		32, // If_stmt
		31, // Expr
		5,  // Term
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S28
		-1, // S'
		34, // Stmt
		23, // If_stmt
		22, // Expr
		5,  // Term
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		37, // Expr
		14, // Term
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S37
		-1, // S'
		39, // Stmt
		23, // If_stmt
		22, // Expr
		5,  // Term
	},
	gotoRow{ // S38
		-1, // S'
		40, // Stmt
		32, // If_stmt
		31, // Expr
		5,  // Term
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S41
		-1, // S'
		43, // Stmt
		32, // If_stmt
		31, // Expr
		5,  // Term
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Stmt
		-1, // If_stmt
		-1, // Expr
		-1, // Term
	},
}
