/*

Event Log BNF

Copyright (c) 2022 Tong Sun

*/

/* Lexical part */


_digit : '0'-'9' ;

_jobLog     : 'H'  'R'  'I'  'm'  'p'  'o'  'r'  't'  'J'  'o'  'b' ;

_lineend : [ '\r' ] '\n' ;

timestamp
  : _digit _digit _digit _digit '-' _digit _digit '-' _digit _digit
    ' ' _digit _digit ':' _digit _digit ':' _digit _digit '.' { _digit } ' '
  ;

jobLogStart     : _jobLog' '  'R'  'u'  'n'  'n'  'i'  'n'  'g'  ' '  'j'  'o'  'b' _lineend ;
processLogStart : 'S'  't'  'a'  'r'  't'  ' '  'o'  'f'  ' ' { . } _lineend;
taskLogStart 	: 'S'  't'  'a'  'r'  't'  ' ' { . } _lineend;
taskLogEnd 	: 'E'  'n'  'd'  ' ' { . } _lineend;
processLogEnd  	: 'E'  'n'  'd'  ' '  'o'  'f'  ' ' { . } _lineend;
jobLogEnd     	: _jobLog ' '  'J'  'o'  'b'  ' '  'c'  'o'  'm'  'p'  'l'  'e'  't'  'e'  'd' _lineend ;


/* Syntax part */

<< 
import (
	"github.com/suntong/lang/lang/Go/src/parsers/gocc/psr2-logp/ast"
	//"github.com/suntong/lang/lang/Go/src/parsers/gocc/psr2-logp/token"
)
>>

EventLog
  : JobLog					<< "", nil >>
  ;

JobLog
  : JobLogStart ProcessLog JobLogEnd
  ;

ProcessLog
  : ProcessLogStart TaskLog ProcessLogEnd
  ;

TaskLog
  : TaskLogStart TaskLogEnd		<< ast.Pair($0.(string),
						$1.(string)), nil >>
  | TaskLog
    TaskLogStart TaskLogEnd
  ;

TaskLogStart : timestamp taskLogStart	<< ast.AttribToString($0) +
	       		 		   ast.AttribToString($1), nil >> ;
TaskLogEnd   : timestamp  taskLogEnd	<< ast.AttribToString($0), nil >>  ;

ProcessLogStart : timestamp processLogStart ;
ProcessLogEnd   : timestamp  processLogEnd  ;

JobLogStart : timestamp jobLogStart ;
JobLogEnd   : timestamp  jobLogEnd  ;

