// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // :
			nil,      // ;
			shift(4), // ident
			nil,      // terminal
			nil,      // [
			nil,      // ]
			nil,      // {
			nil,      // }
			nil,      // (
			nil,      // )
			nil,      // |
			nil,      // ,
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // :
			nil,          // ;
			shift(4),     // ident
			nil,          // terminal
			nil,          // [
			nil,          // ]
			nil,          // {
			nil,          // }
			nil,          // (
			nil,          // )
			nil,          // |
			nil,          // ,
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Grammar
			nil,       // :
			nil,       // ;
			reduce(1), // ident, reduce: Grammar
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(6), // :
			nil,      // ;
			nil,      // ident
			nil,      // terminal
			nil,      // [
			nil,      // ]
			nil,      // {
			nil,      // }
			nil,      // (
			nil,      // )
			nil,      // |
			nil,      // ,
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(4), // :, reduce: Lhs
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Grammar
			nil,       // :
			nil,       // ;
			reduce(2), // ident, reduce: Grammar
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(8),  // ident
			shift(9),  // terminal
			shift(10), // [
			nil,       // ]
			shift(11), // {
			nil,       // }
			shift(12), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			shift(13), // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			shift(14), // |
			shift(15), // ,
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			reduce(5), // ;, reduce: Rhs
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(5), // |, reduce: Rhs
			reduce(5), // ,, reduce: Rhs
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			reduce(6), // ;, reduce: Rhs
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(6), // |, reduce: Rhs
			reduce(6), // ,, reduce: Rhs
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(17), // ident
			shift(18), // terminal
			shift(19), // [
			nil,       // ]
			shift(20), // {
			nil,       // }
			shift(21), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(23), // ident
			shift(24), // terminal
			shift(25), // [
			nil,       // ]
			shift(26), // {
			nil,       // }
			shift(27), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(29), // ident
			shift(30), // terminal
			shift(31), // [
			nil,       // ]
			shift(32), // {
			nil,       // }
			shift(33), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Rule
			nil,       // :
			nil,       // ;
			reduce(3), // ident, reduce: Rule
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(8),  // ident
			shift(9),  // terminal
			shift(10), // [
			nil,       // ]
			shift(11), // {
			nil,       // }
			shift(12), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(8),  // ident
			shift(9),  // terminal
			shift(10), // [
			nil,       // ]
			shift(11), // {
			nil,       // }
			shift(12), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			shift(36), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			shift(37), // |
			shift(38), // ,
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			reduce(5), // ], reduce: Rhs
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(5), // |, reduce: Rhs
			reduce(5), // ,, reduce: Rhs
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			reduce(6), // ], reduce: Rhs
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(6), // |, reduce: Rhs
			reduce(6), // ,, reduce: Rhs
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(17), // ident
			shift(18), // terminal
			shift(19), // [
			nil,       // ]
			shift(20), // {
			nil,       // }
			shift(21), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(23), // ident
			shift(24), // terminal
			shift(25), // [
			nil,       // ]
			shift(26), // {
			nil,       // }
			shift(27), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(29), // ident
			shift(30), // terminal
			shift(31), // [
			nil,       // ]
			shift(32), // {
			nil,       // }
			shift(33), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(42), // }
			nil,       // (
			nil,       // )
			shift(43), // |
			shift(44), // ,
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			reduce(5), // }, reduce: Rhs
			nil,       // (
			nil,       // )
			reduce(5), // |, reduce: Rhs
			reduce(5), // ,, reduce: Rhs
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			reduce(6), // }, reduce: Rhs
			nil,       // (
			nil,       // )
			reduce(6), // |, reduce: Rhs
			reduce(6), // ,, reduce: Rhs
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(17), // ident
			shift(18), // terminal
			shift(19), // [
			nil,       // ]
			shift(20), // {
			nil,       // }
			shift(21), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(23), // ident
			shift(24), // terminal
			shift(25), // [
			nil,       // ]
			shift(26), // {
			nil,       // }
			shift(27), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(29), // ident
			shift(30), // terminal
			shift(31), // [
			nil,       // ]
			shift(32), // {
			nil,       // }
			shift(33), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(48), // )
			shift(49), // |
			shift(50), // ,
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			reduce(5), // ), reduce: Rhs
			reduce(5), // |, reduce: Rhs
			reduce(5), // ,, reduce: Rhs
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			reduce(6), // ), reduce: Rhs
			reduce(6), // |, reduce: Rhs
			reduce(6), // ,, reduce: Rhs
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(17), // ident
			shift(18), // terminal
			shift(19), // [
			nil,       // ]
			shift(20), // {
			nil,       // }
			shift(21), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(23), // ident
			shift(24), // terminal
			shift(25), // [
			nil,       // ]
			shift(26), // {
			nil,       // }
			shift(27), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(29), // ident
			shift(30), // terminal
			shift(31), // [
			nil,       // ]
			shift(32), // {
			nil,       // }
			shift(33), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			reduce(10), // ;, reduce: Rhs
			nil,        // ident
			nil,        // terminal
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // (
			nil,        // )
			shift(14),  // |
			shift(15),  // ,
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			reduce(11), // ;, reduce: Rhs
			nil,        // ident
			nil,        // terminal
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // (
			nil,        // )
			shift(14),  // |
			shift(15),  // ,
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			reduce(7), // ;, reduce: Rhs
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(7), // |, reduce: Rhs
			reduce(7), // ,, reduce: Rhs
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(17), // ident
			shift(18), // terminal
			shift(19), // [
			nil,       // ]
			shift(20), // {
			nil,       // }
			shift(21), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(17), // ident
			shift(18), // terminal
			shift(19), // [
			nil,       // ]
			shift(20), // {
			nil,       // }
			shift(21), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			shift(56), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			shift(37), // |
			shift(38), // ,
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(57), // }
			nil,       // (
			nil,       // )
			shift(43), // |
			shift(44), // ,
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(58), // )
			shift(49), // |
			shift(50), // ,
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			reduce(8), // ;, reduce: Rhs
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(8), // |, reduce: Rhs
			reduce(8), // ,, reduce: Rhs
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(23), // ident
			shift(24), // terminal
			shift(25), // [
			nil,       // ]
			shift(26), // {
			nil,       // }
			shift(27), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(23), // ident
			shift(24), // terminal
			shift(25), // [
			nil,       // ]
			shift(26), // {
			nil,       // }
			shift(27), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			shift(61), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			shift(37), // |
			shift(38), // ,
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(62), // }
			nil,       // (
			nil,       // )
			shift(43), // |
			shift(44), // ,
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(63), // )
			shift(49), // |
			shift(50), // ,
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			reduce(9), // ;, reduce: Rhs
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(9), // |, reduce: Rhs
			reduce(9), // ,, reduce: Rhs
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(29), // ident
			shift(30), // terminal
			shift(31), // [
			nil,       // ]
			shift(32), // {
			nil,       // }
			shift(33), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			shift(29), // ident
			shift(30), // terminal
			shift(31), // [
			nil,       // ]
			shift(32), // {
			nil,       // }
			shift(33), // (
			nil,       // )
			nil,       // |
			nil,       // ,
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			shift(66), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			shift(37), // |
			shift(38), // ,
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(67), // }
			nil,       // (
			nil,       // )
			shift(43), // |
			shift(44), // ,
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(68), // )
			shift(49), // |
			shift(50), // ,
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			nil,        // ;
			nil,        // ident
			nil,        // terminal
			nil,        // [
			reduce(10), // ], reduce: Rhs
			nil,        // {
			nil,        // }
			nil,        // (
			nil,        // )
			shift(37),  // |
			shift(38),  // ,
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			nil,        // ;
			nil,        // ident
			nil,        // terminal
			nil,        // [
			reduce(11), // ], reduce: Rhs
			nil,        // {
			nil,        // }
			nil,        // (
			nil,        // )
			shift(37),  // |
			shift(38),  // ,
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			reduce(7), // ], reduce: Rhs
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(7), // |, reduce: Rhs
			reduce(7), // ,, reduce: Rhs
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			reduce(8), // ], reduce: Rhs
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(8), // |, reduce: Rhs
			reduce(8), // ,, reduce: Rhs
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			reduce(9), // ], reduce: Rhs
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
			reduce(9), // |, reduce: Rhs
			reduce(9), // ,, reduce: Rhs
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			nil,        // ;
			nil,        // ident
			nil,        // terminal
			nil,        // [
			nil,        // ]
			nil,        // {
			reduce(10), // }, reduce: Rhs
			nil,        // (
			nil,        // )
			shift(43),  // |
			shift(44),  // ,
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			nil,        // ;
			nil,        // ident
			nil,        // terminal
			nil,        // [
			nil,        // ]
			nil,        // {
			reduce(11), // }, reduce: Rhs
			nil,        // (
			nil,        // )
			shift(43),  // |
			shift(44),  // ,
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			reduce(7), // }, reduce: Rhs
			nil,       // (
			nil,       // )
			reduce(7), // |, reduce: Rhs
			reduce(7), // ,, reduce: Rhs
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			reduce(8), // }, reduce: Rhs
			nil,       // (
			nil,       // )
			reduce(8), // |, reduce: Rhs
			reduce(8), // ,, reduce: Rhs
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			reduce(9), // }, reduce: Rhs
			nil,       // (
			nil,       // )
			reduce(9), // |, reduce: Rhs
			reduce(9), // ,, reduce: Rhs
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			nil,        // ;
			nil,        // ident
			nil,        // terminal
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // (
			reduce(10), // ), reduce: Rhs
			shift(49),  // |
			shift(50),  // ,
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // :
			nil,        // ;
			nil,        // ident
			nil,        // terminal
			nil,        // [
			nil,        // ]
			nil,        // {
			nil,        // }
			nil,        // (
			reduce(11), // ), reduce: Rhs
			shift(49),  // |
			shift(50),  // ,
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			reduce(7), // ), reduce: Rhs
			reduce(7), // |, reduce: Rhs
			reduce(7), // ,, reduce: Rhs
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			reduce(8), // ), reduce: Rhs
			reduce(8), // |, reduce: Rhs
			reduce(8), // ,, reduce: Rhs
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // :
			nil,       // ;
			nil,       // ident
			nil,       // terminal
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			reduce(9), // ), reduce: Rhs
			reduce(9), // |, reduce: Rhs
			reduce(9), // ,, reduce: Rhs
		},
	},
}
