// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Grammar
		2,  // Rule
		3,  // Lhs
		-1, // Rhs
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Grammar
		5,  // Rule
		3,  // Lhs
		-1, // Rhs
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		7,  // Rhs
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		16, // Rhs
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		22, // Rhs
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		28, // Rhs
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		34, // Rhs
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		35, // Rhs
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		39, // Rhs
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		40, // Rhs
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		41, // Rhs
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		45, // Rhs
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		46, // Rhs
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		47, // Rhs
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		51, // Rhs
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		52, // Rhs
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		53, // Rhs
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		54, // Rhs
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		55, // Rhs
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		59, // Rhs
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		60, // Rhs
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		64, // Rhs
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		65, // Rhs
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Grammar
		-1, // Rule
		-1, // Lhs
		-1, // Rhs
	},
}
