package xo_mssql

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Ufngetsalesorderstatustext calls the stored function 'dbo.ufnGetSalesOrderStatusText(tinyint) nvarchar' on db.
func Ufngetsalesorderstatustext(ctx context.Context, db DB, status bool) (string, error) {
	// call dbo.ufnGetSalesOrderStatusText
	const sqlstr = `SELECT dbo.ufnGetSalesOrderStatusText(@p1) AS OUT`
	// run
	var r0 string
	logf(sqlstr, status)
	if err := db.QueryRowContext(ctx, sqlstr, status).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
