package xo_mssql

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Usplogerror calls the stored procedure 'dbo.uspLogError() int' on db.
func Usplogerror(ctx context.Context, db DB) (int, error) {
	// call dbo.uspLogError
	const sqlstr = `dbo.uspLogError`
	// run
	var errorLogID int
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, sql.Named("ErrorLogID", sql.Out{Dest: &errorLogID})); err != nil {
		return 0, logerror(err)
	}
	return errorLogID, nil
}
