// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 9

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Program
		4,  // ProgramDef
		6,  // Procedure
		5,  // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Program
		9,  // ProgramDef
		6,  // Procedure
		5,  // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		12, // ProgramBody
		14, // ForLoop
		13, // Assignment
		-1, // RHS
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		20, // ForLoop
		19, // Assignment
		-1, // RHS
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		24, // Assignment
		-1, // RHS
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		25, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		29, // RHS
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		34, // Assignment
		-1, // RHS
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		37, // ProgramBody
		14, // ForLoop
		13, // Assignment
		-1, // RHS
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		41, // RHS
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		20, // ForLoop
		19, // Assignment
		-1, // RHS
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		50, // Assignment
		-1, // RHS
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		51, // Assignment
		-1, // RHS
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		55, // RHS
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Program
		-1, // ProgramDef
		-1, // Procedure
		-1, // BeginBlock
		-1, // ProgramBody
		-1, // ForLoop
		-1, // Assignment
		-1, // RHS
	},
}
