// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(3), // id
			nil,      // ::=
			nil,      // ;
			nil,      // |
			nil,      // .
			nil,      // char_lit
			nil,      // -
			nil,      // string_lit
			nil,      // url_lit
			nil,      // repeat_char
			nil,      // [
			nil,      // ]
			nil,      // {
			nil,      // }
			nil,      // (
			nil,      // )
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			shift(3),     // id
			nil,          // ::=
			nil,          // ;
			nil,          // |
			nil,          // .
			nil,          // char_lit
			nil,          // -
			nil,          // string_lit
			nil,          // url_lit
			nil,          // repeat_char
			nil,          // [
			nil,          // ]
			nil,          // {
			nil,          // }
			nil,          // (
			nil,          // )
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Grammar
			reduce(1), // id, reduce: Grammar
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // id
			shift(5), // ::=
			nil,      // ;
			nil,      // |
			nil,      // .
			nil,      // char_lit
			nil,      // -
			nil,      // string_lit
			nil,      // url_lit
			nil,      // repeat_char
			nil,      // [
			nil,      // ]
			nil,      // {
			nil,      // }
			nil,      // (
			nil,      // )
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Grammar
			reduce(2), // id, reduce: Grammar
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(6),  // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(10), // .
			shift(11), // char_lit
			nil,       // -
			shift(12), // string_lit
			shift(13), // url_lit
			nil,       // repeat_char
			shift(14), // [
			nil,       // ]
			shift(15), // {
			nil,       // }
			shift(16), // (
			nil,       // )
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // id, reduce: LexTerm
			nil,       // ::=
			reduce(9), // ;, reduce: LexTerm
			reduce(9), // |, reduce: LexTerm
			reduce(9), // ., reduce: LexTerm
			reduce(9), // char_lit, reduce: LexTerm
			reduce(9), // -, reduce: LexTerm
			reduce(9), // string_lit, reduce: LexTerm
			reduce(9), // url_lit, reduce: LexTerm
			reduce(9), // repeat_char, reduce: LexTerm
			reduce(9), // [, reduce: LexTerm
			nil,       // ]
			reduce(9), // {, reduce: LexTerm
			nil,       // }
			reduce(9), // (, reduce: LexTerm
			nil,       // )
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			shift(17), // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(6),  // id
			nil,       // ::=
			reduce(4), // ;, reduce: LexPattern
			shift(18), // |
			shift(10), // .
			shift(11), // char_lit
			nil,       // -
			shift(12), // string_lit
			shift(13), // url_lit
			nil,       // repeat_char
			shift(14), // [
			nil,       // ]
			shift(15), // {
			nil,       // }
			shift(16), // (
			nil,       // )
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // id, reduce: LexAlt
			nil,       // ::=
			reduce(6), // ;, reduce: LexAlt
			reduce(6), // |, reduce: LexAlt
			reduce(6), // ., reduce: LexAlt
			reduce(6), // char_lit, reduce: LexAlt
			shift(20), // -
			reduce(6), // string_lit, reduce: LexAlt
			reduce(6), // url_lit, reduce: LexAlt
			shift(21), // repeat_char
			reduce(6), // [, reduce: LexAlt
			nil,       // ]
			reduce(6), // {, reduce: LexAlt
			nil,       // }
			reduce(6), // (, reduce: LexAlt
			nil,       // )
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // id, reduce: LexTerm
			nil,       // ::=
			reduce(8), // ;, reduce: LexTerm
			reduce(8), // |, reduce: LexTerm
			reduce(8), // ., reduce: LexTerm
			reduce(8), // char_lit, reduce: LexTerm
			reduce(8), // -, reduce: LexTerm
			reduce(8), // string_lit, reduce: LexTerm
			reduce(8), // url_lit, reduce: LexTerm
			reduce(8), // repeat_char, reduce: LexTerm
			reduce(8), // [, reduce: LexTerm
			nil,       // ]
			reduce(8), // {, reduce: LexTerm
			nil,       // }
			reduce(8), // (, reduce: LexTerm
			nil,       // )
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // id, reduce: LexTerm
			nil,        // ::=
			reduce(10), // ;, reduce: LexTerm
			reduce(10), // |, reduce: LexTerm
			reduce(10), // ., reduce: LexTerm
			reduce(10), // char_lit, reduce: LexTerm
			reduce(10), // -, reduce: LexTerm
			reduce(10), // string_lit, reduce: LexTerm
			reduce(10), // url_lit, reduce: LexTerm
			reduce(10), // repeat_char, reduce: LexTerm
			reduce(10), // [, reduce: LexTerm
			nil,        // ]
			reduce(10), // {, reduce: LexTerm
			nil,        // }
			reduce(10), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(12), // id, reduce: LexTerm
			nil,        // ::=
			reduce(12), // ;, reduce: LexTerm
			reduce(12), // |, reduce: LexTerm
			reduce(12), // ., reduce: LexTerm
			reduce(12), // char_lit, reduce: LexTerm
			reduce(12), // -, reduce: LexTerm
			reduce(12), // string_lit, reduce: LexTerm
			reduce(12), // url_lit, reduce: LexTerm
			reduce(12), // repeat_char, reduce: LexTerm
			reduce(12), // [, reduce: LexTerm
			nil,        // ]
			reduce(12), // {, reduce: LexTerm
			nil,        // }
			reduce(12), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(13), // id, reduce: LexTerm
			nil,        // ::=
			reduce(13), // ;, reduce: LexTerm
			reduce(13), // |, reduce: LexTerm
			reduce(13), // ., reduce: LexTerm
			reduce(13), // char_lit, reduce: LexTerm
			reduce(13), // -, reduce: LexTerm
			reduce(13), // string_lit, reduce: LexTerm
			reduce(13), // url_lit, reduce: LexTerm
			reduce(13), // repeat_char, reduce: LexTerm
			reduce(13), // [, reduce: LexTerm
			nil,        // ]
			reduce(13), // {, reduce: LexTerm
			nil,        // }
			reduce(13), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			nil,       // -
			shift(28), // string_lit
			shift(29), // url_lit
			nil,       // repeat_char
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			shift(32), // (
			nil,       // )
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(33), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(37), // .
			shift(38), // char_lit
			nil,       // -
			shift(39), // string_lit
			shift(40), // url_lit
			nil,       // repeat_char
			shift(41), // [
			nil,       // ]
			shift(42), // {
			nil,       // }
			shift(43), // (
			nil,       // )
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(44), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(48), // .
			shift(49), // char_lit
			nil,       // -
			shift(50), // string_lit
			shift(51), // url_lit
			nil,       // repeat_char
			shift(52), // [
			nil,       // ]
			shift(53), // {
			nil,       // }
			shift(54), // (
			nil,       // )
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Production
			reduce(3), // id, reduce: Production
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(6),  // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(10), // .
			shift(11), // char_lit
			nil,       // -
			shift(12), // string_lit
			shift(13), // url_lit
			nil,       // repeat_char
			shift(14), // [
			nil,       // ]
			shift(15), // {
			nil,       // }
			shift(16), // (
			nil,       // )
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // id, reduce: LexAlt
			nil,       // ::=
			reduce(7), // ;, reduce: LexAlt
			reduce(7), // |, reduce: LexAlt
			reduce(7), // ., reduce: LexAlt
			reduce(7), // char_lit, reduce: LexAlt
			shift(20), // -
			reduce(7), // string_lit, reduce: LexAlt
			reduce(7), // url_lit, reduce: LexAlt
			shift(21), // repeat_char
			reduce(7), // [, reduce: LexAlt
			nil,       // ]
			reduce(7), // {, reduce: LexAlt
			nil,       // }
			reduce(7), // (, reduce: LexAlt
			nil,       // )
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			shift(56), // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(14), // id, reduce: LexTerm
			nil,        // ::=
			reduce(14), // ;, reduce: LexTerm
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // -, reduce: LexTerm
			reduce(14), // string_lit, reduce: LexTerm
			reduce(14), // url_lit, reduce: LexTerm
			reduce(14), // repeat_char, reduce: LexTerm
			reduce(14), // [, reduce: LexTerm
			nil,        // ]
			reduce(14), // {, reduce: LexTerm
			nil,        // }
			reduce(14), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // id, reduce: LexTerm
			nil,       // ::=
			nil,       // ;
			reduce(9), // |, reduce: LexTerm
			reduce(9), // ., reduce: LexTerm
			reduce(9), // char_lit, reduce: LexTerm
			reduce(9), // -, reduce: LexTerm
			reduce(9), // string_lit, reduce: LexTerm
			reduce(9), // url_lit, reduce: LexTerm
			reduce(9), // repeat_char, reduce: LexTerm
			reduce(9), // [, reduce: LexTerm
			reduce(9), // ], reduce: LexTerm
			reduce(9), // {, reduce: LexTerm
			nil,       // }
			reduce(9), // (, reduce: LexTerm
			nil,       // )
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			shift(57), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // id
			nil,       // ::=
			nil,       // ;
			shift(58), // |
			shift(26), // .
			shift(27), // char_lit
			nil,       // -
			shift(28), // string_lit
			shift(29), // url_lit
			nil,       // repeat_char
			shift(30), // [
			reduce(4), // ], reduce: LexPattern
			shift(31), // {
			nil,       // }
			shift(32), // (
			nil,       // )
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // id, reduce: LexAlt
			nil,       // ::=
			nil,       // ;
			reduce(6), // |, reduce: LexAlt
			reduce(6), // ., reduce: LexAlt
			reduce(6), // char_lit, reduce: LexAlt
			shift(60), // -
			reduce(6), // string_lit, reduce: LexAlt
			reduce(6), // url_lit, reduce: LexAlt
			shift(61), // repeat_char
			reduce(6), // [, reduce: LexAlt
			reduce(6), // ], reduce: LexAlt
			reduce(6), // {, reduce: LexAlt
			nil,       // }
			reduce(6), // (, reduce: LexAlt
			nil,       // )
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // id, reduce: LexTerm
			nil,       // ::=
			nil,       // ;
			reduce(8), // |, reduce: LexTerm
			reduce(8), // ., reduce: LexTerm
			reduce(8), // char_lit, reduce: LexTerm
			reduce(8), // -, reduce: LexTerm
			reduce(8), // string_lit, reduce: LexTerm
			reduce(8), // url_lit, reduce: LexTerm
			reduce(8), // repeat_char, reduce: LexTerm
			reduce(8), // [, reduce: LexTerm
			reduce(8), // ], reduce: LexTerm
			reduce(8), // {, reduce: LexTerm
			nil,       // }
			reduce(8), // (, reduce: LexTerm
			nil,       // )
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(10), // |, reduce: LexTerm
			reduce(10), // ., reduce: LexTerm
			reduce(10), // char_lit, reduce: LexTerm
			reduce(10), // -, reduce: LexTerm
			reduce(10), // string_lit, reduce: LexTerm
			reduce(10), // url_lit, reduce: LexTerm
			reduce(10), // repeat_char, reduce: LexTerm
			reduce(10), // [, reduce: LexTerm
			reduce(10), // ], reduce: LexTerm
			reduce(10), // {, reduce: LexTerm
			nil,        // }
			reduce(10), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(12), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(12), // |, reduce: LexTerm
			reduce(12), // ., reduce: LexTerm
			reduce(12), // char_lit, reduce: LexTerm
			reduce(12), // -, reduce: LexTerm
			reduce(12), // string_lit, reduce: LexTerm
			reduce(12), // url_lit, reduce: LexTerm
			reduce(12), // repeat_char, reduce: LexTerm
			reduce(12), // [, reduce: LexTerm
			reduce(12), // ], reduce: LexTerm
			reduce(12), // {, reduce: LexTerm
			nil,        // }
			reduce(12), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(13), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(13), // |, reduce: LexTerm
			reduce(13), // ., reduce: LexTerm
			reduce(13), // char_lit, reduce: LexTerm
			reduce(13), // -, reduce: LexTerm
			reduce(13), // string_lit, reduce: LexTerm
			reduce(13), // url_lit, reduce: LexTerm
			reduce(13), // repeat_char, reduce: LexTerm
			reduce(13), // [, reduce: LexTerm
			reduce(13), // ], reduce: LexTerm
			reduce(13), // {, reduce: LexTerm
			nil,        // }
			reduce(13), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			nil,       // -
			shift(28), // string_lit
			shift(29), // url_lit
			nil,       // repeat_char
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			shift(32), // (
			nil,       // )
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(33), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(37), // .
			shift(38), // char_lit
			nil,       // -
			shift(39), // string_lit
			shift(40), // url_lit
			nil,       // repeat_char
			shift(41), // [
			nil,       // ]
			shift(42), // {
			nil,       // }
			shift(43), // (
			nil,       // )
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(44), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(48), // .
			shift(49), // char_lit
			nil,       // -
			shift(50), // string_lit
			shift(51), // url_lit
			nil,       // repeat_char
			shift(52), // [
			nil,       // ]
			shift(53), // {
			nil,       // }
			shift(54), // (
			nil,       // )
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // id, reduce: LexTerm
			nil,       // ::=
			nil,       // ;
			reduce(9), // |, reduce: LexTerm
			reduce(9), // ., reduce: LexTerm
			reduce(9), // char_lit, reduce: LexTerm
			reduce(9), // -, reduce: LexTerm
			reduce(9), // string_lit, reduce: LexTerm
			reduce(9), // url_lit, reduce: LexTerm
			reduce(9), // repeat_char, reduce: LexTerm
			reduce(9), // [, reduce: LexTerm
			nil,       // ]
			reduce(9), // {, reduce: LexTerm
			reduce(9), // }, reduce: LexTerm
			reduce(9), // (, reduce: LexTerm
			nil,       // )
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(65), // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(33), // id
			nil,       // ::=
			nil,       // ;
			shift(66), // |
			shift(37), // .
			shift(38), // char_lit
			nil,       // -
			shift(39), // string_lit
			shift(40), // url_lit
			nil,       // repeat_char
			shift(41), // [
			nil,       // ]
			shift(42), // {
			reduce(4), // }, reduce: LexPattern
			shift(43), // (
			nil,       // )
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // id, reduce: LexAlt
			nil,       // ::=
			nil,       // ;
			reduce(6), // |, reduce: LexAlt
			reduce(6), // ., reduce: LexAlt
			reduce(6), // char_lit, reduce: LexAlt
			shift(68), // -
			reduce(6), // string_lit, reduce: LexAlt
			reduce(6), // url_lit, reduce: LexAlt
			shift(69), // repeat_char
			reduce(6), // [, reduce: LexAlt
			nil,       // ]
			reduce(6), // {, reduce: LexAlt
			reduce(6), // }, reduce: LexAlt
			reduce(6), // (, reduce: LexAlt
			nil,       // )
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // id, reduce: LexTerm
			nil,       // ::=
			nil,       // ;
			reduce(8), // |, reduce: LexTerm
			reduce(8), // ., reduce: LexTerm
			reduce(8), // char_lit, reduce: LexTerm
			reduce(8), // -, reduce: LexTerm
			reduce(8), // string_lit, reduce: LexTerm
			reduce(8), // url_lit, reduce: LexTerm
			reduce(8), // repeat_char, reduce: LexTerm
			reduce(8), // [, reduce: LexTerm
			nil,       // ]
			reduce(8), // {, reduce: LexTerm
			reduce(8), // }, reduce: LexTerm
			reduce(8), // (, reduce: LexTerm
			nil,       // )
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(10), // |, reduce: LexTerm
			reduce(10), // ., reduce: LexTerm
			reduce(10), // char_lit, reduce: LexTerm
			reduce(10), // -, reduce: LexTerm
			reduce(10), // string_lit, reduce: LexTerm
			reduce(10), // url_lit, reduce: LexTerm
			reduce(10), // repeat_char, reduce: LexTerm
			reduce(10), // [, reduce: LexTerm
			nil,        // ]
			reduce(10), // {, reduce: LexTerm
			reduce(10), // }, reduce: LexTerm
			reduce(10), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(12), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(12), // |, reduce: LexTerm
			reduce(12), // ., reduce: LexTerm
			reduce(12), // char_lit, reduce: LexTerm
			reduce(12), // -, reduce: LexTerm
			reduce(12), // string_lit, reduce: LexTerm
			reduce(12), // url_lit, reduce: LexTerm
			reduce(12), // repeat_char, reduce: LexTerm
			reduce(12), // [, reduce: LexTerm
			nil,        // ]
			reduce(12), // {, reduce: LexTerm
			reduce(12), // }, reduce: LexTerm
			reduce(12), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(13), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(13), // |, reduce: LexTerm
			reduce(13), // ., reduce: LexTerm
			reduce(13), // char_lit, reduce: LexTerm
			reduce(13), // -, reduce: LexTerm
			reduce(13), // string_lit, reduce: LexTerm
			reduce(13), // url_lit, reduce: LexTerm
			reduce(13), // repeat_char, reduce: LexTerm
			reduce(13), // [, reduce: LexTerm
			nil,        // ]
			reduce(13), // {, reduce: LexTerm
			reduce(13), // }, reduce: LexTerm
			reduce(13), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			nil,       // -
			shift(28), // string_lit
			shift(29), // url_lit
			nil,       // repeat_char
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			shift(32), // (
			nil,       // )
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(33), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(37), // .
			shift(38), // char_lit
			nil,       // -
			shift(39), // string_lit
			shift(40), // url_lit
			nil,       // repeat_char
			shift(41), // [
			nil,       // ]
			shift(42), // {
			nil,       // }
			shift(43), // (
			nil,       // )
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(44), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(48), // .
			shift(49), // char_lit
			nil,       // -
			shift(50), // string_lit
			shift(51), // url_lit
			nil,       // repeat_char
			shift(52), // [
			nil,       // ]
			shift(53), // {
			nil,       // }
			shift(54), // (
			nil,       // )
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // id, reduce: LexTerm
			nil,       // ::=
			nil,       // ;
			reduce(9), // |, reduce: LexTerm
			reduce(9), // ., reduce: LexTerm
			reduce(9), // char_lit, reduce: LexTerm
			reduce(9), // -, reduce: LexTerm
			reduce(9), // string_lit, reduce: LexTerm
			reduce(9), // url_lit, reduce: LexTerm
			reduce(9), // repeat_char, reduce: LexTerm
			reduce(9), // [, reduce: LexTerm
			nil,       // ]
			reduce(9), // {, reduce: LexTerm
			nil,       // }
			reduce(9), // (, reduce: LexTerm
			reduce(9), // ), reduce: LexTerm
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(73), // )
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(44), // id
			nil,       // ::=
			nil,       // ;
			shift(74), // |
			shift(48), // .
			shift(49), // char_lit
			nil,       // -
			shift(50), // string_lit
			shift(51), // url_lit
			nil,       // repeat_char
			shift(52), // [
			nil,       // ]
			shift(53), // {
			nil,       // }
			shift(54), // (
			reduce(4), // ), reduce: LexPattern
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // id, reduce: LexAlt
			nil,       // ::=
			nil,       // ;
			reduce(6), // |, reduce: LexAlt
			reduce(6), // ., reduce: LexAlt
			reduce(6), // char_lit, reduce: LexAlt
			shift(76), // -
			reduce(6), // string_lit, reduce: LexAlt
			reduce(6), // url_lit, reduce: LexAlt
			shift(77), // repeat_char
			reduce(6), // [, reduce: LexAlt
			nil,       // ]
			reduce(6), // {, reduce: LexAlt
			nil,       // }
			reduce(6), // (, reduce: LexAlt
			reduce(6), // ), reduce: LexAlt
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // id, reduce: LexTerm
			nil,       // ::=
			nil,       // ;
			reduce(8), // |, reduce: LexTerm
			reduce(8), // ., reduce: LexTerm
			reduce(8), // char_lit, reduce: LexTerm
			reduce(8), // -, reduce: LexTerm
			reduce(8), // string_lit, reduce: LexTerm
			reduce(8), // url_lit, reduce: LexTerm
			reduce(8), // repeat_char, reduce: LexTerm
			reduce(8), // [, reduce: LexTerm
			nil,       // ]
			reduce(8), // {, reduce: LexTerm
			nil,       // }
			reduce(8), // (, reduce: LexTerm
			reduce(8), // ), reduce: LexTerm
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(10), // |, reduce: LexTerm
			reduce(10), // ., reduce: LexTerm
			reduce(10), // char_lit, reduce: LexTerm
			reduce(10), // -, reduce: LexTerm
			reduce(10), // string_lit, reduce: LexTerm
			reduce(10), // url_lit, reduce: LexTerm
			reduce(10), // repeat_char, reduce: LexTerm
			reduce(10), // [, reduce: LexTerm
			nil,        // ]
			reduce(10), // {, reduce: LexTerm
			nil,        // }
			reduce(10), // (, reduce: LexTerm
			reduce(10), // ), reduce: LexTerm
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(12), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(12), // |, reduce: LexTerm
			reduce(12), // ., reduce: LexTerm
			reduce(12), // char_lit, reduce: LexTerm
			reduce(12), // -, reduce: LexTerm
			reduce(12), // string_lit, reduce: LexTerm
			reduce(12), // url_lit, reduce: LexTerm
			reduce(12), // repeat_char, reduce: LexTerm
			reduce(12), // [, reduce: LexTerm
			nil,        // ]
			reduce(12), // {, reduce: LexTerm
			nil,        // }
			reduce(12), // (, reduce: LexTerm
			reduce(12), // ), reduce: LexTerm
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(13), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(13), // |, reduce: LexTerm
			reduce(13), // ., reduce: LexTerm
			reduce(13), // char_lit, reduce: LexTerm
			reduce(13), // -, reduce: LexTerm
			reduce(13), // string_lit, reduce: LexTerm
			reduce(13), // url_lit, reduce: LexTerm
			reduce(13), // repeat_char, reduce: LexTerm
			reduce(13), // [, reduce: LexTerm
			nil,        // ]
			reduce(13), // {, reduce: LexTerm
			nil,        // }
			reduce(13), // (, reduce: LexTerm
			reduce(13), // ), reduce: LexTerm
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			nil,       // -
			shift(28), // string_lit
			shift(29), // url_lit
			nil,       // repeat_char
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			shift(32), // (
			nil,       // )
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(33), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(37), // .
			shift(38), // char_lit
			nil,       // -
			shift(39), // string_lit
			shift(40), // url_lit
			nil,       // repeat_char
			shift(41), // [
			nil,       // ]
			shift(42), // {
			nil,       // }
			shift(43), // (
			nil,       // )
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(44), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(48), // .
			shift(49), // char_lit
			nil,       // -
			shift(50), // string_lit
			shift(51), // url_lit
			nil,       // repeat_char
			shift(52), // [
			nil,       // ]
			shift(53), // {
			nil,       // }
			shift(54), // (
			nil,       // )
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			reduce(5), // ;, reduce: LexPattern
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(11), // id, reduce: LexTerm
			nil,        // ::=
			reduce(11), // ;, reduce: LexTerm
			reduce(11), // |, reduce: LexTerm
			reduce(11), // ., reduce: LexTerm
			reduce(11), // char_lit, reduce: LexTerm
			reduce(11), // -, reduce: LexTerm
			reduce(11), // string_lit, reduce: LexTerm
			reduce(11), // url_lit, reduce: LexTerm
			reduce(11), // repeat_char, reduce: LexTerm
			reduce(11), // [, reduce: LexTerm
			nil,        // ]
			reduce(11), // {, reduce: LexTerm
			nil,        // }
			reduce(11), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(15), // id, reduce: LexTerm
			nil,        // ::=
			reduce(15), // ;, reduce: LexTerm
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // -, reduce: LexTerm
			reduce(15), // string_lit, reduce: LexTerm
			reduce(15), // url_lit, reduce: LexTerm
			reduce(15), // repeat_char, reduce: LexTerm
			reduce(15), // [, reduce: LexTerm
			nil,        // ]
			reduce(15), // {, reduce: LexTerm
			nil,        // }
			reduce(15), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(26), // .
			shift(27), // char_lit
			nil,       // -
			shift(28), // string_lit
			shift(29), // url_lit
			nil,       // repeat_char
			shift(30), // [
			nil,       // ]
			shift(31), // {
			nil,       // }
			shift(32), // (
			nil,       // )
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // id, reduce: LexAlt
			nil,       // ::=
			nil,       // ;
			reduce(7), // |, reduce: LexAlt
			reduce(7), // ., reduce: LexAlt
			reduce(7), // char_lit, reduce: LexAlt
			shift(60), // -
			reduce(7), // string_lit, reduce: LexAlt
			reduce(7), // url_lit, reduce: LexAlt
			shift(61), // repeat_char
			reduce(7), // [, reduce: LexAlt
			reduce(7), // ], reduce: LexAlt
			reduce(7), // {, reduce: LexAlt
			nil,       // }
			reduce(7), // (, reduce: LexAlt
			nil,       // )
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			shift(82), // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(14), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // -, reduce: LexTerm
			reduce(14), // string_lit, reduce: LexTerm
			reduce(14), // url_lit, reduce: LexTerm
			reduce(14), // repeat_char, reduce: LexTerm
			reduce(14), // [, reduce: LexTerm
			reduce(14), // ], reduce: LexTerm
			reduce(14), // {, reduce: LexTerm
			nil,        // }
			reduce(14), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			shift(83), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(84), // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(85), // )
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(16), // id, reduce: LexTerm
			nil,        // ::=
			reduce(16), // ;, reduce: LexTerm
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // -, reduce: LexTerm
			reduce(16), // string_lit, reduce: LexTerm
			reduce(16), // url_lit, reduce: LexTerm
			reduce(16), // repeat_char, reduce: LexTerm
			reduce(16), // [, reduce: LexTerm
			nil,        // ]
			reduce(16), // {, reduce: LexTerm
			nil,        // }
			reduce(16), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(33), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(37), // .
			shift(38), // char_lit
			nil,       // -
			shift(39), // string_lit
			shift(40), // url_lit
			nil,       // repeat_char
			shift(41), // [
			nil,       // ]
			shift(42), // {
			nil,       // }
			shift(43), // (
			nil,       // )
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // id, reduce: LexAlt
			nil,       // ::=
			nil,       // ;
			reduce(7), // |, reduce: LexAlt
			reduce(7), // ., reduce: LexAlt
			reduce(7), // char_lit, reduce: LexAlt
			shift(68), // -
			reduce(7), // string_lit, reduce: LexAlt
			reduce(7), // url_lit, reduce: LexAlt
			shift(69), // repeat_char
			reduce(7), // [, reduce: LexAlt
			nil,       // ]
			reduce(7), // {, reduce: LexAlt
			reduce(7), // }, reduce: LexAlt
			reduce(7), // (, reduce: LexAlt
			nil,       // )
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			shift(87), // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(14), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // -, reduce: LexTerm
			reduce(14), // string_lit, reduce: LexTerm
			reduce(14), // url_lit, reduce: LexTerm
			reduce(14), // repeat_char, reduce: LexTerm
			reduce(14), // [, reduce: LexTerm
			nil,        // ]
			reduce(14), // {, reduce: LexTerm
			reduce(14), // }, reduce: LexTerm
			reduce(14), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			shift(88), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(89), // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(90), // )
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(17), // id, reduce: LexTerm
			nil,        // ::=
			reduce(17), // ;, reduce: LexTerm
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // -, reduce: LexTerm
			reduce(17), // string_lit, reduce: LexTerm
			reduce(17), // url_lit, reduce: LexTerm
			reduce(17), // repeat_char, reduce: LexTerm
			reduce(17), // [, reduce: LexTerm
			nil,        // ]
			reduce(17), // {, reduce: LexTerm
			nil,        // }
			reduce(17), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(44), // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			shift(48), // .
			shift(49), // char_lit
			nil,       // -
			shift(50), // string_lit
			shift(51), // url_lit
			nil,       // repeat_char
			shift(52), // [
			nil,       // ]
			shift(53), // {
			nil,       // }
			shift(54), // (
			nil,       // )
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // id, reduce: LexAlt
			nil,       // ::=
			nil,       // ;
			reduce(7), // |, reduce: LexAlt
			reduce(7), // ., reduce: LexAlt
			reduce(7), // char_lit, reduce: LexAlt
			shift(76), // -
			reduce(7), // string_lit, reduce: LexAlt
			reduce(7), // url_lit, reduce: LexAlt
			shift(77), // repeat_char
			reduce(7), // [, reduce: LexAlt
			nil,       // ]
			reduce(7), // {, reduce: LexAlt
			nil,       // }
			reduce(7), // (, reduce: LexAlt
			reduce(7), // ), reduce: LexAlt
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			shift(92), // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(14), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(14), // |, reduce: LexTerm
			reduce(14), // ., reduce: LexTerm
			reduce(14), // char_lit, reduce: LexTerm
			reduce(14), // -, reduce: LexTerm
			reduce(14), // string_lit, reduce: LexTerm
			reduce(14), // url_lit, reduce: LexTerm
			reduce(14), // repeat_char, reduce: LexTerm
			reduce(14), // [, reduce: LexTerm
			nil,        // ]
			reduce(14), // {, reduce: LexTerm
			nil,        // }
			reduce(14), // (, reduce: LexTerm
			reduce(14), // ), reduce: LexTerm
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			shift(93), // ]
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			shift(94), // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			shift(95), // )
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			reduce(5), // ], reduce: LexPattern
			nil,       // {
			nil,       // }
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(11), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(11), // |, reduce: LexTerm
			reduce(11), // ., reduce: LexTerm
			reduce(11), // char_lit, reduce: LexTerm
			reduce(11), // -, reduce: LexTerm
			reduce(11), // string_lit, reduce: LexTerm
			reduce(11), // url_lit, reduce: LexTerm
			reduce(11), // repeat_char, reduce: LexTerm
			reduce(11), // [, reduce: LexTerm
			reduce(11), // ], reduce: LexTerm
			reduce(11), // {, reduce: LexTerm
			nil,        // }
			reduce(11), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(15), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // -, reduce: LexTerm
			reduce(15), // string_lit, reduce: LexTerm
			reduce(15), // url_lit, reduce: LexTerm
			reduce(15), // repeat_char, reduce: LexTerm
			reduce(15), // [, reduce: LexTerm
			reduce(15), // ], reduce: LexTerm
			reduce(15), // {, reduce: LexTerm
			nil,        // }
			reduce(15), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(16), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // -, reduce: LexTerm
			reduce(16), // string_lit, reduce: LexTerm
			reduce(16), // url_lit, reduce: LexTerm
			reduce(16), // repeat_char, reduce: LexTerm
			reduce(16), // [, reduce: LexTerm
			reduce(16), // ], reduce: LexTerm
			reduce(16), // {, reduce: LexTerm
			nil,        // }
			reduce(16), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(17), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // -, reduce: LexTerm
			reduce(17), // string_lit, reduce: LexTerm
			reduce(17), // url_lit, reduce: LexTerm
			reduce(17), // repeat_char, reduce: LexTerm
			reduce(17), // [, reduce: LexTerm
			reduce(17), // ], reduce: LexTerm
			reduce(17), // {, reduce: LexTerm
			nil,        // }
			reduce(17), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			reduce(5), // }, reduce: LexPattern
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(11), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(11), // |, reduce: LexTerm
			reduce(11), // ., reduce: LexTerm
			reduce(11), // char_lit, reduce: LexTerm
			reduce(11), // -, reduce: LexTerm
			reduce(11), // string_lit, reduce: LexTerm
			reduce(11), // url_lit, reduce: LexTerm
			reduce(11), // repeat_char, reduce: LexTerm
			reduce(11), // [, reduce: LexTerm
			nil,        // ]
			reduce(11), // {, reduce: LexTerm
			reduce(11), // }, reduce: LexTerm
			reduce(11), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(15), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // -, reduce: LexTerm
			reduce(15), // string_lit, reduce: LexTerm
			reduce(15), // url_lit, reduce: LexTerm
			reduce(15), // repeat_char, reduce: LexTerm
			reduce(15), // [, reduce: LexTerm
			nil,        // ]
			reduce(15), // {, reduce: LexTerm
			reduce(15), // }, reduce: LexTerm
			reduce(15), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(16), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // -, reduce: LexTerm
			reduce(16), // string_lit, reduce: LexTerm
			reduce(16), // url_lit, reduce: LexTerm
			reduce(16), // repeat_char, reduce: LexTerm
			reduce(16), // [, reduce: LexTerm
			nil,        // ]
			reduce(16), // {, reduce: LexTerm
			reduce(16), // }, reduce: LexTerm
			reduce(16), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(17), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // -, reduce: LexTerm
			reduce(17), // string_lit, reduce: LexTerm
			reduce(17), // url_lit, reduce: LexTerm
			reduce(17), // repeat_char, reduce: LexTerm
			reduce(17), // [, reduce: LexTerm
			nil,        // ]
			reduce(17), // {, reduce: LexTerm
			reduce(17), // }, reduce: LexTerm
			reduce(17), // (, reduce: LexTerm
			nil,        // )
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // id
			nil,       // ::=
			nil,       // ;
			nil,       // |
			nil,       // .
			nil,       // char_lit
			nil,       // -
			nil,       // string_lit
			nil,       // url_lit
			nil,       // repeat_char
			nil,       // [
			nil,       // ]
			nil,       // {
			nil,       // }
			nil,       // (
			reduce(5), // ), reduce: LexPattern
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(11), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(11), // |, reduce: LexTerm
			reduce(11), // ., reduce: LexTerm
			reduce(11), // char_lit, reduce: LexTerm
			reduce(11), // -, reduce: LexTerm
			reduce(11), // string_lit, reduce: LexTerm
			reduce(11), // url_lit, reduce: LexTerm
			reduce(11), // repeat_char, reduce: LexTerm
			reduce(11), // [, reduce: LexTerm
			nil,        // ]
			reduce(11), // {, reduce: LexTerm
			nil,        // }
			reduce(11), // (, reduce: LexTerm
			reduce(11), // ), reduce: LexTerm
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(15), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(15), // |, reduce: LexTerm
			reduce(15), // ., reduce: LexTerm
			reduce(15), // char_lit, reduce: LexTerm
			reduce(15), // -, reduce: LexTerm
			reduce(15), // string_lit, reduce: LexTerm
			reduce(15), // url_lit, reduce: LexTerm
			reduce(15), // repeat_char, reduce: LexTerm
			reduce(15), // [, reduce: LexTerm
			nil,        // ]
			reduce(15), // {, reduce: LexTerm
			nil,        // }
			reduce(15), // (, reduce: LexTerm
			reduce(15), // ), reduce: LexTerm
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(16), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(16), // |, reduce: LexTerm
			reduce(16), // ., reduce: LexTerm
			reduce(16), // char_lit, reduce: LexTerm
			reduce(16), // -, reduce: LexTerm
			reduce(16), // string_lit, reduce: LexTerm
			reduce(16), // url_lit, reduce: LexTerm
			reduce(16), // repeat_char, reduce: LexTerm
			reduce(16), // [, reduce: LexTerm
			nil,        // ]
			reduce(16), // {, reduce: LexTerm
			nil,        // }
			reduce(16), // (, reduce: LexTerm
			reduce(16), // ), reduce: LexTerm
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(17), // id, reduce: LexTerm
			nil,        // ::=
			nil,        // ;
			reduce(17), // |, reduce: LexTerm
			reduce(17), // ., reduce: LexTerm
			reduce(17), // char_lit, reduce: LexTerm
			reduce(17), // -, reduce: LexTerm
			reduce(17), // string_lit, reduce: LexTerm
			reduce(17), // url_lit, reduce: LexTerm
			reduce(17), // repeat_char, reduce: LexTerm
			reduce(17), // [, reduce: LexTerm
			nil,        // ]
			reduce(17), // {, reduce: LexTerm
			nil,        // }
			reduce(17), // (, reduce: LexTerm
			reduce(17), // ), reduce: LexTerm
		},
	},
}
