// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 6

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Grammar
		2,  // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Grammar
		4,  // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Grammar
		-1, // Production
		7,  // LexPattern
		8,  // LexAlt
		9,  // LexTerm
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		19, // LexTerm
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Grammar
		-1, // Production
		23, // LexPattern
		24, // LexAlt
		25, // LexTerm
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Grammar
		-1, // Production
		34, // LexPattern
		35, // LexAlt
		36, // LexTerm
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Grammar
		-1, // Production
		45, // LexPattern
		46, // LexAlt
		47, // LexTerm
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Grammar
		-1, // Production
		55, // LexPattern
		8,  // LexAlt
		9,  // LexTerm
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		59, // LexTerm
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Grammar
		-1, // Production
		62, // LexPattern
		24, // LexAlt
		25, // LexTerm
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Grammar
		-1, // Production
		63, // LexPattern
		35, // LexAlt
		36, // LexTerm
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Grammar
		-1, // Production
		64, // LexPattern
		46, // LexAlt
		47, // LexTerm
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		67, // LexTerm
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Grammar
		-1, // Production
		70, // LexPattern
		24, // LexAlt
		25, // LexTerm
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Grammar
		-1, // Production
		71, // LexPattern
		35, // LexAlt
		36, // LexTerm
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Grammar
		-1, // Production
		72, // LexPattern
		46, // LexAlt
		47, // LexTerm
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		75, // LexTerm
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Grammar
		-1, // Production
		78, // LexPattern
		24, // LexAlt
		25, // LexTerm
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Grammar
		-1, // Production
		79, // LexPattern
		35, // LexAlt
		36, // LexTerm
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Grammar
		-1, // Production
		80, // LexPattern
		46, // LexAlt
		47, // LexTerm
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Grammar
		-1, // Production
		81, // LexPattern
		24, // LexAlt
		25, // LexTerm
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Grammar
		-1, // Production
		86, // LexPattern
		35, // LexAlt
		36, // LexTerm
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S69
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S70
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S71
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S72
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S73
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S74
		-1, // S'
		-1, // Grammar
		-1, // Production
		91, // LexPattern
		46, // LexAlt
		47, // LexTerm
	},
	gotoRow{ // S75
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S76
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S77
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S78
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S79
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S80
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S81
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S82
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S83
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S84
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S85
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S86
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S87
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S88
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S89
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S90
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S91
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S92
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S93
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S94
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
	gotoRow{ // S95
		-1, // S'
		-1, // Grammar
		-1, // Production
		-1, // LexPattern
		-1, // LexAlt
		-1, // LexTerm
	},
}
