
/* Lexical part */

_digit : '0'-'9' ;

_timestamp1 : _digit | ' ' | ':' | '-' | '.' ;

timestamp       : _timestamp1 { _timestamp1 } ; 
ignore :  '['  { . } ' '  '-'  ' '  'M'  'Y'  'K'  'W'  ' '  '-'  ' ' ;
//blockComment : '/' '*' { . | '*' } '*' '/' ;
blockComment : '[' _digit { . | '*' } '*' '/' ;


/* Syntax part */

<< 
import (
	// "github.com/suntong/gocc-grammars/bnf/token"
	// "github.com/suntong/gocc-grammars/bnf/util"
)
>>


Log
 : timestamp ignore
 | blockComment Log
 ;
