
/* Lexical part */

_digit : '0'-'9' ;
_timestamp1 : _digit | ' ' | ':' | '-' | '.' ;
_timestamp2 : _digit | ' ' | ':' | '/' | 'A' | 'P' | 'M' ;
_lineend : [ '\r' ] '\n' ;

timestamp       : _timestamp1 { _timestamp1 } ;
ignore : '[' _digit { . | ' ' } ' ' '-' ;
mykw : ' '  'M'  'Y'  'K'  'W'  ' '  '-'  ' ' ;

taskLogStart 	: 'S'  't'  'a'  'r'  't' ;
jobName : ' '  { . } ':' ;

timestamp2 	: _timestamp2 { _timestamp2 } _lineend ;
// error: expected jobName; got: unknown/invalid token " Ac"

Log
 : timestamp ignore mykw taskLogStart jobName
 ;
