
/* Lexical part */

_digit : '0'-'9' ;

ignore : '[' _digit { . | ' ' } ' ' '-' ;
mykw : ' '  'M'  'Y'  'K'  'W'  ' '  '-'  ' ' ;

taskLogStart 	: 'S'  't'  'a'  'r'  't' ;
jobName : ' '  { . } ':' ;

Log
 : ignore mykw taskLogStart jobName
 ;
