
/* Lexical part */

// ignore : '[' _digit { . | ' ' } ' ' '-' ;
mykw : ' '  'M'  'Y'  'K'  'W'  ' '  '-'  ' ' ;

taskLogStart 	: 'S'  't'  'a'  'r'  't' ;
jobName : ' '  { . } ':' ;

Log
 : mykw taskLogStart jobName
 ;
