
/* Lexical part */

_digit : '0'-'9' ;
_lineend : [ '\r' ] '\n' ;

timestamp
  : _digit _digit _digit _digit '-' _digit _digit '-' _digit _digit
    ' ' _digit _digit ':' _digit _digit ':' _digit _digit '.' { _digit }
  ;
ignore : ' '  '[' _digit { . | ' ' } ' ' '-' ;
mykw : ' '  'M'  'Y'  'K'  'W'  ' '  '-'  ' ' ;

taskLogStart 	: 'S'  't'  'a'  'r'  't' ;
jobName : ' '  { . } ':' ;

ignore2 :  ' ' {.} '\n';

Log
 : timestamp ignore mykw taskLogStart jobName ignore2
 ;

/*

Token at Pos(offset=24, line=1, column=25): jobName " [21] These are strings that I need to ignore, until - MYKW - Start Active One:"
    line_test.go:25: 1:25: error: expected ignore; got: " [21] These are strings that I need to ignore, until - MYKW - Start Active One:"

*/

// Because it is context-free grammar!!!!

