// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/suntong/lang/lang/Go/src/parsers/gocc/grm3-pascal/token"
)

const (
	NoState    = -1
	NumStates  = 98
	NumSymbols = 83
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '-'
1: '"'
2: '"'
3: '''
4: '''
5: '"'
6: '"'
7: 'P'
8: 'R'
9: 'O'
10: 'G'
11: 'R'
12: 'A'
13: 'M'
14: 'P'
15: 'R'
16: 'O'
17: 'C'
18: 'E'
19: 'D'
20: 'U'
21: 'R'
22: 'E'
23: '('
24: ')'
25: 'B'
26: 'E'
27: 'G'
28: 'I'
29: 'N'
30: 'E'
31: 'N'
32: 'D'
33: '.'
34: ';'
35: 'F'
36: 'O'
37: 'R'
38: 'T'
39: 'O'
40: 'D'
41: 'O'
42: ':'
43: '='
44: '/'
45: '/'
46: '\n'
47: '/'
48: '*'
49: '*'
50: '*'
51: '/'
52: '_'
53: '\'
54: '\'
55: 'x'
56: '\'
57: 'u'
58: '\'
59: 'U'
60: '\'
61: 'a'
62: 'b'
63: 'f'
64: 'n'
65: 'r'
66: 't'
67: 'v'
68: '\'
69: '''
70: '"'
71: ' '
72: '\t'
73: '\n'
74: '\r'
75: 'A'-'Z'
76: 'a'-'z'
77: '0'-'9'
78: '0'-'7'
79: '0'-'9'
80: 'A'-'F'
81: 'a'-'f'
82: .
*/
