// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 3

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Content
		2,  // Title
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Content
		9,  // Title
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Content
		-1, // Title
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Content
		-1, // Title
	},
}
