/*

EBNF
https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form#EBNF

Copyright (c) 2021 Tong Sun

*/

/* Lexical part */
_whitespace : ' ' | '\t' | '\v' | '\f' | '\r' | '\n';

!whitespace : _whitespace;
!lineComment  : '/' '/' { . } '\n' ;
!blockComment : '/' '*' { . | '*' } '*' '/' ;

_letter : 'A'-'Z' | 'a'-'z' | '_' ;
_digit : '0'-'9' ;

/* punctuation */
minus : '-' ;
bar : '|' ;
lbrace : '{' ;
rbrace : '}' ;
lparen : '(' ;
rparen : ')' ;

lend : '[' ;
rend : ']' ;

_symbol
  : '!' |  '#' - '/'  |  ':' - '@'  |  '[' - '^'
  ;

_alpha : _letter | _digit ;

_character
  : _letter | _digit | _symbol
  ;

colon : ':' ;
semicolon : ';' ;

ident
  : ['!'] _letter { _alpha }
  ;

character: _character ;

terminal
  : '\''  _character   { _character }  '\'' 
  | '"'   _character   { _character }   '"' 
  | '.'
  | '\''  (_whitespace)  '\''
  ;


/* Syntax part */

<< 
import (
	// "github.com/suntong/gocc-grammars/bnf/token"
	// "github.com/suntong/gocc-grammars/bnf/util"
)
>>

Grammar
  : Rule
  | Grammar Rule
  ;

Rule
  : Lhs colon Rhs semicolon
  ;

Lhs
  : ident
  ;

Rhs
  : ident
  | terminal
  | terminal character
  | Rhs  lend   Rhs  rend
  | Rhs  lbrace Rhs  rbrace
  | Rhs  lparen Rhs  rparen
  | Rhs  bar    Rhs
//| Rhs   ","   Rhs
  | character minus character
  | character
  | empty
  ;
