// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 2

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Hello
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Hello
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Hello
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Hello
	},
}
