
/* Lexical part */
!whitespace : ' ' | '\t' | '\n' | '\r' ;

_nl : [ '\r' ] '\n' ;

title6 : {_nl} '#' '#' '#' '#' '#' '#' {.} _nl {_nl} ;
title5 : {_nl} '#' '#' '#' '#' '#' {.} _nl {_nl} ;
title4 : {_nl} '#' '#' '#' '#' {.} _nl {_nl} ;
title3 : {_nl} '#' '#' '#' {.} _nl {_nl} ;
title2 : {_nl} '#' '#' {.} _nl {_nl} ;
title1 : {_nl} '#' {.} _nl {_nl} ;


/* Syntax part */

<< 
import (
	"github.com/suntong/lang/lang/Go/src/parsers/gocc/psr7-mdtitle/ast"
)
>>

Content
  : Title
  | Content Title	<< $0.(string) + $1.(string), nil >>
  ;

Title
  : title6	<< ast.AttribToString($0), nil >>
  | title5	<< ast.AttribToString($0), nil >>
  | title4	<< ast.AttribToString($0), nil >>
  | title3	<< ast.AttribToString($0), nil >>
  | title2	<< ast.AttribToString($0), nil >>
  | title1	<< ast.AttribToString($0), nil >>
  ;
