// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/suntong/lang/lang/Go/src/parsers/gocc/psr2-logp/token"
)

const (
	NoState    = -1
	NumStates  = 89
	NumSymbols = 74
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '-'
1: '-'
2: ' '
3: ':'
4: ':'
5: '.'
6: ' '
7: ' '
8: 'R'
9: 'u'
10: 'n'
11: 'n'
12: 'i'
13: 'n'
14: 'g'
15: ' '
16: 'j'
17: 'o'
18: 'b'
19: 'S'
20: 't'
21: 'a'
22: 'r'
23: 't'
24: ' '
25: 'o'
26: 'f'
27: ' '
28: 'S'
29: 't'
30: 'a'
31: 'r'
32: 't'
33: ' '
34: 'E'
35: 'n'
36: 'd'
37: ' '
38: 'E'
39: 'n'
40: 'd'
41: ' '
42: 'o'
43: 'f'
44: ' '
45: ' '
46: 'J'
47: 'o'
48: 'b'
49: ' '
50: 'c'
51: 'o'
52: 'm'
53: 'p'
54: 'l'
55: 'e'
56: 't'
57: 'e'
58: 'd'
59: 'H'
60: 'R'
61: 'I'
62: 'm'
63: 'p'
64: 'o'
65: 'r'
66: 't'
67: 'J'
68: 'o'
69: 'b'
70: '\r'
71: '\n'
72: '0'-'9'
73: .
*/
