left_Paren : ( ;

right_Paren : ) ;

asterisk : * ;

plus_Sign : + ;

comma : , ;

minus_Sign : - ;

period : . ;

solidus : / ;

colon : : ;

less_Than_Operator : < ;

equals_Operator : = ;

greater_Than_Operator : > ;

question_Mark : ? ;

unsigned_Numeric_Literal :
		exact_Numeric_Literal
	|	approximate_Numeric_Literal ;

unsigned_Integer : digit ... ;

approximate_Numeric_Literal :
		mantissa E exponent ;

mantissa : exact_Numeric_Literal ;

exponent : signed_Integer ;

sign : plus_Sign | minus_Sign ;

character_Set_Specification :
		standard_Character_Repertoire_Name
	|	implementation-defined_Character_Repertoire_Name
	|	user-defined_Character_Repertoire_Name
	|	standard_Universal_Character_Form-of-use_Name
	|	implementation-defined_Universal_Character_Form-of-use_Name ;

standard_Character_Repertoire_Name : character_Set_Name ;

catalog_Name : identifier ;

actual_Identifier : regular_Identifier | delimited_Identifier ;

delimited_Identifier : double_Quote delimited_Identifier_Body double_Quote ;

delimited_Identifier_Body : delimited_Identifier_Part... ;

unqualified_Schema_Name : identifier ;

sQL_Language_Identifier_Start : simple_Latin_Letter ;

sQL_Language_Identifier_Part : simple_Latin_Letter | digit ;

not_Equals_Operator :  ;

greater_Than_Or_Equals_Operator : >= ;

less_Than_Or_Equals_Operator : <= ;

concatenation_Operator : || ;

authorization_Identifier : identifier ;

qualified_Local_Table_Name : MODULE period local_Table_Name ;

local_Table_Name : qualified_Identifier ;

qualified_Identifier : identifier ;

table_Element : column_Definition | table_Constraint_Definition ;

column_Name : identifier ;

length : unsigned_Integer ;

numeric_Type :
		exact_Numeric_Type
	|	approximate_Numeric_Type ;

precision : unsigned_Integer ;

scale : unsigned_Integer ;

time_Precision : time_Fractional_Seconds_Precision ;

time_Fractional_Seconds_Precision : unsigned_Integer ;

timestamp_Precision : time_Fractional_Seconds_Precision ;

interval_Type : INTERVAL interval_Qualifier ;

interval_Qualifier :
		start_Field TO end_Field
	|   single_Datetime_Field ;

interval_Leading_Field_Precision : unsigned_Integer ;

interval_Fractional_Seconds_Precision : unsigned_Integer ;

domain_Name : qualified_Name ;

default_Clause : DEFAULT default_Option ;

default_Option :
		literal
	|	datetime_Value_Function
	|	USER
	|	CURRENT_USER
	|	SESSION_USER
	|	SYSTEM_USER
	|	NULL ;

literal : signed_Numeric_Literal | general_Literal ;

general_Literal :
		character_String_Literal
	|	national_Character_String_Literal
	|	bit_String_Literal
	|	hex_String_Literal
	|	datetime_Literal
	|	interval_Literal ;

datetime_Literal :
		date_Literal
	|	time_Literal
	|	timestamp_Literal ;

date_Literal : DATE date_String ;

time_Literal : TIME time_String ;

timestamp_Literal : TIMESTAMP timestamp_String ;

datetime_Value_Function :
		current_Date_Value_Function
	|	current_Time_Value_Function
	|	current_Timestamp_Value_Function ;

current_Date_Value_Function : CURRENT_DATE ;

simple_Latin_Letter :
		simple_Latin_Upper_Case_Letter
	|	simple_Latin_Lower_Case_Letter ;

simple_Latin_Upper_Case_Letter :
	A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z ;

simple_Latin_Lower_Case_Letter :
	a | b | c | d | e | f | g | h | i | j | k | l | m | n | o | p | q | r | s | t | u | v | w | x | y | z ;

digit :
	0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ;

double_Quote : " ;

underscore : _ ;

regular_Identifier : identifier_Body ;

identifier_Start : !! See the Syntax rules ;

identifier_Part : identifier_Start | digit ;

character_Representation : nonquote_Character | quote_Symbol ;

nonquote_Character : !! See the Syntax rules ;

quote_Symbol : quote quote ;

bit : 0 | 1 ;

hexit : digit | A | B | C | D | E | F | a | b | c | d | e | f ;

date_String : quote date_Value quote ;

date_Value : years_Value minus_Sign months_Value minus_Sign days_Value ;

years_Value : datetime_Value ;

datetime_Value : unsigned_Integer ;

months_Value : datetime_Value ;

days_Value : datetime_Value ;

time_Value : hours_Value colon minutes_Value colon seconds_Value ;

hours_Value : datetime_Value ;

minutes_Value : datetime_Value ;

seconds_Integer_Value : unsigned_Integer ;

seconds_Fraction : unsigned_Integer ;

time_Zone_Interval : sign hours_Value colon minutes_Value ;

space : !! space character in character set in use ;

quote : ' ;

