// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // ;
			shift(4), // reg
			nil,      // =
			nil,      // +
			nil,      // -
			nil,      // *
			nil,      // /
			shift(7), // (
			nil,      // )
			shift(8), // int64
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			shift(9),     // ;
			nil,          // reg
			nil,          // =
			nil,          // +
			nil,          // -
			nil,          // *
			nil,          // /
			nil,          // (
			nil,          // )
			nil,          // int64
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Calcs
			reduce(1), // ;, reduce: Calcs
			nil,       // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Calc
			reduce(3), // ;, reduce: Calc
			nil,       // reg
			nil,       // =
			shift(10), // +
			shift(11), // -
			nil,       // *
			nil,       // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // $, reduce: Factor
			reduce(13), // ;, reduce: Factor
			nil,        // reg
			shift(12),  // =
			reduce(13), // +, reduce: Factor
			reduce(13), // -, reduce: Factor
			reduce(13), // *, reduce: Factor
			reduce(13), // /, reduce: Factor
			nil,        // (
			nil,        // )
			nil,        // int64
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: Expr
			reduce(7), // ;, reduce: Expr
			nil,       // reg
			nil,       // =
			reduce(7), // +, reduce: Expr
			reduce(7), // -, reduce: Expr
			shift(13), // *
			shift(14), // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: Term
			reduce(10), // ;, reduce: Term
			nil,        // reg
			nil,        // =
			reduce(10), // +, reduce: Term
			reduce(10), // -, reduce: Term
			reduce(10), // *, reduce: Term
			reduce(10), // /, reduce: Term
			nil,        // (
			nil,        // )
			nil,        // int64
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(16), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(19), // (
			nil,       // )
			shift(20), // int64
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // $, reduce: Factor
			reduce(12), // ;, reduce: Factor
			nil,        // reg
			nil,        // =
			reduce(12), // +, reduce: Factor
			reduce(12), // -, reduce: Factor
			reduce(12), // *, reduce: Factor
			reduce(12), // /, reduce: Factor
			nil,        // (
			nil,        // )
			nil,        // int64
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // ;
			shift(4), // reg
			nil,      // =
			nil,      // +
			nil,      // -
			nil,      // *
			nil,      // /
			shift(7), // (
			nil,      // )
			shift(8), // int64
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(22), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(7),  // (
			nil,       // )
			shift(8),  // int64
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(22), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(7),  // (
			nil,       // )
			shift(8),  // int64
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(22), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(7),  // (
			nil,       // )
			shift(8),  // int64
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(22), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(7),  // (
			nil,       // )
			shift(8),  // int64
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(22), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(7),  // (
			nil,       // )
			shift(8),  // int64
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			shift(28), // +
			shift(29), // -
			nil,       // *
			nil,       // /
			nil,       // (
			shift(30), // )
			nil,       // int64
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // ;
			nil,        // reg
			nil,        // =
			reduce(13), // +, reduce: Factor
			reduce(13), // -, reduce: Factor
			reduce(13), // *, reduce: Factor
			reduce(13), // /, reduce: Factor
			nil,        // (
			reduce(13), // ), reduce: Factor
			nil,        // int64
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			reduce(7), // +, reduce: Expr
			reduce(7), // -, reduce: Expr
			shift(31), // *
			shift(32), // /
			nil,       // (
			reduce(7), // ), reduce: Expr
			nil,       // int64
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // ;
			nil,        // reg
			nil,        // =
			reduce(10), // +, reduce: Term
			reduce(10), // -, reduce: Term
			reduce(10), // *, reduce: Term
			reduce(10), // /, reduce: Term
			nil,        // (
			reduce(10), // ), reduce: Term
			nil,        // int64
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(16), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(19), // (
			nil,       // )
			shift(20), // int64
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // ;
			nil,        // reg
			nil,        // =
			reduce(12), // +, reduce: Factor
			reduce(12), // -, reduce: Factor
			reduce(12), // *, reduce: Factor
			reduce(12), // /, reduce: Factor
			nil,        // (
			reduce(12), // ), reduce: Factor
			nil,        // int64
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Calcs
			reduce(2), // ;, reduce: Calcs
			nil,       // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // $, reduce: Factor
			reduce(13), // ;, reduce: Factor
			nil,        // reg
			nil,        // =
			reduce(13), // +, reduce: Factor
			reduce(13), // -, reduce: Factor
			reduce(13), // *, reduce: Factor
			reduce(13), // /, reduce: Factor
			nil,        // (
			nil,        // )
			nil,        // int64
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: Expr
			reduce(5), // ;, reduce: Expr
			nil,       // reg
			nil,       // =
			reduce(5), // +, reduce: Expr
			reduce(5), // -, reduce: Expr
			shift(13), // *
			shift(14), // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Expr
			reduce(6), // ;, reduce: Expr
			nil,       // reg
			nil,       // =
			reduce(6), // +, reduce: Expr
			reduce(6), // -, reduce: Expr
			shift(13), // *
			shift(14), // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: Calc
			reduce(4), // ;, reduce: Calc
			nil,       // reg
			nil,       // =
			shift(10), // +
			shift(11), // -
			nil,       // *
			nil,       // /
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: Term
			reduce(8), // ;, reduce: Term
			nil,       // reg
			nil,       // =
			reduce(8), // +, reduce: Term
			reduce(8), // -, reduce: Term
			reduce(8), // *, reduce: Term
			reduce(8), // /, reduce: Term
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // $, reduce: Term
			reduce(9), // ;, reduce: Term
			nil,       // reg
			nil,       // =
			reduce(9), // +, reduce: Term
			reduce(9), // -, reduce: Term
			reduce(9), // *, reduce: Term
			reduce(9), // /, reduce: Term
			nil,       // (
			nil,       // )
			nil,       // int64
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(16), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(19), // (
			nil,       // )
			shift(20), // int64
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(16), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(19), // (
			nil,       // )
			shift(20), // int64
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // $, reduce: Factor
			reduce(11), // ;, reduce: Factor
			nil,        // reg
			nil,        // =
			reduce(11), // +, reduce: Factor
			reduce(11), // -, reduce: Factor
			reduce(11), // *, reduce: Factor
			reduce(11), // /, reduce: Factor
			nil,        // (
			nil,        // )
			nil,        // int64
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(16), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(19), // (
			nil,       // )
			shift(20), // int64
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			shift(16), // reg
			nil,       // =
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			shift(19), // (
			nil,       // )
			shift(20), // int64
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			shift(28), // +
			shift(29), // -
			nil,       // *
			nil,       // /
			nil,       // (
			shift(38), // )
			nil,       // int64
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			reduce(5), // +, reduce: Expr
			reduce(5), // -, reduce: Expr
			shift(31), // *
			shift(32), // /
			nil,       // (
			reduce(5), // ), reduce: Expr
			nil,       // int64
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			reduce(6), // +, reduce: Expr
			reduce(6), // -, reduce: Expr
			shift(31), // *
			shift(32), // /
			nil,       // (
			reduce(6), // ), reduce: Expr
			nil,       // int64
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			reduce(8), // +, reduce: Term
			reduce(8), // -, reduce: Term
			reduce(8), // *, reduce: Term
			reduce(8), // /, reduce: Term
			nil,       // (
			reduce(8), // ), reduce: Term
			nil,       // int64
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // ;
			nil,       // reg
			nil,       // =
			reduce(9), // +, reduce: Term
			reduce(9), // -, reduce: Term
			reduce(9), // *, reduce: Term
			reduce(9), // /, reduce: Term
			nil,       // (
			reduce(9), // ), reduce: Term
			nil,       // int64
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // ;
			nil,        // reg
			nil,        // =
			reduce(11), // +, reduce: Factor
			reduce(11), // -, reduce: Factor
			reduce(11), // *, reduce: Factor
			reduce(11), // /, reduce: Factor
			nil,        // (
			reduce(11), // ), reduce: Factor
			nil,        // int64
		},
	},
}
