// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(3), // title6
			shift(4), // title5
			shift(5), // title4
			shift(6), // title3
			shift(7), // title2
			shift(8), // title1
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			shift(3),     // title6
			shift(4),     // title5
			shift(5),     // title4
			shift(6),     // title3
			shift(7),     // title2
			shift(8),     // title1
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Content
			reduce(1), // title6, reduce: Content
			reduce(1), // title5, reduce: Content
			reduce(1), // title4, reduce: Content
			reduce(1), // title3, reduce: Content
			reduce(1), // title2, reduce: Content
			reduce(1), // title1, reduce: Content
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Title
			reduce(3), // title6, reduce: Title
			reduce(3), // title5, reduce: Title
			reduce(3), // title4, reduce: Title
			reduce(3), // title3, reduce: Title
			reduce(3), // title2, reduce: Title
			reduce(3), // title1, reduce: Title
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: Title
			reduce(4), // title6, reduce: Title
			reduce(4), // title5, reduce: Title
			reduce(4), // title4, reduce: Title
			reduce(4), // title3, reduce: Title
			reduce(4), // title2, reduce: Title
			reduce(4), // title1, reduce: Title
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: Title
			reduce(5), // title6, reduce: Title
			reduce(5), // title5, reduce: Title
			reduce(5), // title4, reduce: Title
			reduce(5), // title3, reduce: Title
			reduce(5), // title2, reduce: Title
			reduce(5), // title1, reduce: Title
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Title
			reduce(6), // title6, reduce: Title
			reduce(6), // title5, reduce: Title
			reduce(6), // title4, reduce: Title
			reduce(6), // title3, reduce: Title
			reduce(6), // title2, reduce: Title
			reduce(6), // title1, reduce: Title
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: Title
			reduce(7), // title6, reduce: Title
			reduce(7), // title5, reduce: Title
			reduce(7), // title4, reduce: Title
			reduce(7), // title3, reduce: Title
			reduce(7), // title2, reduce: Title
			reduce(7), // title1, reduce: Title
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: Title
			reduce(8), // title6, reduce: Title
			reduce(8), // title5, reduce: Title
			reduce(8), // title4, reduce: Title
			reduce(8), // title3, reduce: Title
			reduce(8), // title2, reduce: Title
			reduce(8), // title1, reduce: Title
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Content
			reduce(2), // title6, reduce: Content
			reduce(2), // title5, reduce: Content
			reduce(2), // title4, reduce: Content
			reduce(2), // title3, reduce: Content
			reduce(2), // title2, reduce: Content
			reduce(2), // title1, reduce: Content
		},
	},
}
