// Code generated by gocc; DO NOT EDIT.

package parser

import (
	"github.com/suntong/lang/lang/Go/src/parsers/gocc/psr3-mdtitle/ast"
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Content	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Content : Title	<<  >>`,
		Id:         "Content",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Content : Content Title	<< X[0].(string) + X[1].(string), nil >>`,
		Id:         "Content",
		NTType:     1,
		Index:      2,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0].(string) + X[1].(string), nil
		},
	},
	ProdTabEntry{
		String: `Title : title6	<< ast.AttribToString(X[0]), nil >>`,
		Id:         "Title",
		NTType:     2,
		Index:      3,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AttribToString(X[0]), nil
		},
	},
	ProdTabEntry{
		String: `Title : title5	<< ast.AttribToString(X[0]), nil >>`,
		Id:         "Title",
		NTType:     2,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AttribToString(X[0]), nil
		},
	},
	ProdTabEntry{
		String: `Title : title4	<< ast.AttribToString(X[0]), nil >>`,
		Id:         "Title",
		NTType:     2,
		Index:      5,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AttribToString(X[0]), nil
		},
	},
	ProdTabEntry{
		String: `Title : title3	<< ast.AttribToString(X[0]), nil >>`,
		Id:         "Title",
		NTType:     2,
		Index:      6,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AttribToString(X[0]), nil
		},
	},
	ProdTabEntry{
		String: `Title : title2	<< ast.AttribToString(X[0]), nil >>`,
		Id:         "Title",
		NTType:     2,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AttribToString(X[0]), nil
		},
	},
	ProdTabEntry{
		String: `Title : title1	<< ast.AttribToString(X[0]), nil >>`,
		Id:         "Title",
		NTType:     2,
		Index:      8,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AttribToString(X[0]), nil
		},
	},
}
