// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 2
		case r == 35: // ['#','#']
			return 3
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 2
		case r == 35: // ['#','#']
			return 3
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 1
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 4
		case r == 13: // ['\r','\r']
			return 5
		case r == 35: // ['#','#']
			return 6
		default:
			return 7
		}
	},
	// S4
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 4
		case r == 13: // ['\r','\r']
			return 8
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 4
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 9
		case r == 13: // ['\r','\r']
			return 10
		case r == 35: // ['#','#']
			return 11
		default:
			return 12
		}
	},
	// S7
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 4
		case r == 13: // ['\r','\r']
			return 5
		default:
			return 7
		}
	},
	// S8
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 4
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 9
		case r == 13: // ['\r','\r']
			return 13
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 9
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 14
		case r == 13: // ['\r','\r']
			return 15
		case r == 35: // ['#','#']
			return 16
		default:
			return 17
		}
	},
	// S12
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 9
		case r == 13: // ['\r','\r']
			return 10
		default:
			return 12
		}
	},
	// S13
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 9
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 14
		case r == 13: // ['\r','\r']
			return 18
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 14
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 19
		case r == 13: // ['\r','\r']
			return 20
		case r == 35: // ['#','#']
			return 21
		default:
			return 22
		}
	},
	// S17
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 14
		case r == 13: // ['\r','\r']
			return 15
		default:
			return 17
		}
	},
	// S18
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 14
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 19
		case r == 13: // ['\r','\r']
			return 23
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 19
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 24
		case r == 13: // ['\r','\r']
			return 25
		case r == 35: // ['#','#']
			return 26
		default:
			return 27
		}
	},
	// S22
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 19
		case r == 13: // ['\r','\r']
			return 20
		default:
			return 22
		}
	},
	// S23
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 19
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 24
		case r == 13: // ['\r','\r']
			return 28
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 24
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 29
		case r == 13: // ['\r','\r']
			return 30
		default:
			return 26
		}
	},
	// S27
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 24
		case r == 13: // ['\r','\r']
			return 25
		default:
			return 27
		}
	},
	// S28
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 24
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 29
		case r == 13: // ['\r','\r']
			return 31
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 29
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 29
		}
		return NoState
	},
}
